### ISSUE TITLE
Missing info on expected behaviour for unrecognised annots

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#1]
**Describe the bug**
Section 12.5.1, Paragraph 4:

>An interactive PDF processor shall provide certain expected behaviour for all annotation types that it does not recognise, as documented in 12.5.2, "Annotation dictionaries".

However, there is nothing in 12.5.2 (or anywhere else that I can find) that actually tells a processor (interactive or otherwise) what to do in the case of an unknown annotation _Subtype_.

Recommend that some text be written to define the behavior - or at least to agree that it is undefined.

**Comment by petervwyatt** [comment]
Various related notes:

- PDF 2.0 now requires annot appearance streams (as per Table 166) except for 2 very specific cases which does not include custom annots. So custom/unknown annots still need to have appearance streams.

- Table 167, Bit 1, Invisible says "Applies only to annotations which do not belong to one of the standard annotation types and for which no annotation handler is available. If set, do not render the unknown annotation and do not print it even if the Print flag is set. If clear, render such an unknown annotation using an appearance stream specified by its appearance dictionary, if any (see 12.5.5, "Appearance streams")."

- Table 167, Bit 2, Hidden says "If set, do not render the annotation or allow it to interact with the user, regardless of its annotation type or whether an annotation handler is available."

**Comment by lrosenthol** [comment]
> So custom/unknown annots still need to have appearance streams
>
that is correct - as far as it goes.  But is that then the only "expected behavior" that is mentioned by 12.5.1?

> and for which no annotation handler is available
>
And a processor is only required to have them for the standard types (as defined in 12.5.1, P4) - so yes, we're saying that Invisible has to be handled.
And same with Hidden, OK - that works.

But what about Actions on the annotation?  What about trigger events?

**Comment by petervwyatt** [comment]
You make a really good point - what does "expected behaviour" mean for both non-interactive and interactive viewers, for renderers, for other types of PDF processor (e.g. text extractors, imposition/page extraction engines, etc etc)?

The required Appearance streams in PDF 2.0 only simplifies things and doesn't fully resolve...

**Comment by petervwyatt** [comment]
I also found this in clause 12.5.5:

"If a PDF processor does not have native support for a particular annotation type, the PDF processor shall render the annotation with its normal (N) appearance. PDF processors shall also attempt to provide reasonable behaviour (such as displaying nothing) if an annotation’s **AS** entry designates an appearance state for which no appearance is defined in the appearance dictionary."

**Comment by petervwyatt** [comment]
Trying to progress this forward (in very small steps!)...

Proposal: correct Section 12.5.1, paragraph 4:

> An interactive PDF processor shall provide certain expected behaviour for all annotation types that it does not recognise, as documented in 12.5.2, "Annotation dictionaries".

to:

A PDF processor shall provide certain expected behaviour for all annotation types that it does not recognise, as documented in 12.5.5, "Appearance streams" and "Table 167 - Annotation flags" (bit positions 1 and 2).

@lrosenthol - do you think that is sufficient for what is currently already documented in ISO 32000-2?

**Comment by petervwyatt** [comment]
PDF TWG agree
