### ISSUE TITLE
Type3 FontDescriptors FontName confusion

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#11]
ISO 32000-2:2020 "Table 120 — Entries common to all font descriptors" **FontName** is described as "(_Required_) The PostScript name of the font. This name shall be the same as the value of **BaseFont** in the font or CIDFont dictionary that refers to this font descriptor."

Type3 fonts don't have **BaseName** as defined by Table 110 so therefore the FontDescriptor **FontName** should be not required for Type3.

**Comment by lrosenthol** [comment]
Then how would you know the name of the font, such as for display in a processor's UX?

**Comment by petervwyatt** [comment]
So are you saying "Table 110 — Entries in a Type 3 font dictionary" is incorrect then and needs **BaseFont**?
Or that "Table 120 — Entries common to all font descriptors" **FontName** description is incorrect/incomplete for Type3?

**Comment by lrosenthol** [comment]
did some reading of code and here is the situation...

For Type 3 fonts, the name comes from the `Name` key (if present) in the Type 3 font dictionary. For all other font types, it comes from the `BaseFont` key of the relevant subtype's font dictionary (eg. T1, TTF, etc.).

The `FontName` key in the font descriptor dictionary is used primarily for the purpose of determining if a font has been subset, based on the requirements of 9.9.2 (Font subsets).  

Since Type 3 fonts are either always subset or never subset (depending on how you look at it), there is never a need to have the `FontName` key present in the font descriptor dictionary.  Accordingly, I'd change Table 120 to make it "(Required for non-Type 3 fonts)".

**Comment by petervwyatt** [comment]
Proposed solution: change Table 120 — Entries common to all font descriptors, FontName to say:

(_Required for non-Type 3 fonts_)

**Comment by MPBailey** [comment]
Just saying "Required for non-Type 3 fonts" doesn't say it shall not be there for Type 3, which leads to two problems:
* the rest of the text doesn't make any sense for t3 fonts
* it doesn't make any statement about it having to match anything else for a T3 font.

It may be going a bit overboard, but:

_(Required for fonts other than Type 3)_ The PostScript name of the font. For Type 3 fonts that include a **Name** entry in the Type 3 font dictionary, this name shall match the value of that key. For all fonts other than Type 3 this name shall be the same as the value of **BaseFont** in the font or CIDFont dictionary that refers to this font descriptor.
