### ISSUE TITLE
PDF ISO specification is closed source, hidden-behind-a-paywall and therefore out of reach for community FOSS projects

### ISSUE THREAD

**Issue by pombredanne** [pdf-association/pdf-issues#116]
The PDF 2.0 ISO specification is closed source, hidden-behind-a-paywall and therefore out of reach for community FOSS projects to implement such as https://github.com/pdfminer/pdfminer.six
This is a sad situation. 
What can you do about this?

**Comment by lrosenthol** [comment]
@pombredanne 

Let's clarify a few things here.

1 - ISO standards, such as ISO 32000-2:2020, are just that - standards.  There is no source code, closed or otherwise, involved.

2a - Yes, the ISO does indeed charge for their standards to those that are not involved in their development.  It is one approach used used by standards bodies to be able to pay their employees.
2b - However, one can participate in the *development* of the standard at little to no charge and therefore have not only access to the standard *but* also be able to guide the direction of the standard.

3 - Developers of (F)OSS projects can purchase their own copies of ISO 32000 (or any other standard).  The existence of a "paywall" does not preclude their involvement.  Many (F)OSS projects that work with PDF have obtained access to the standard, either through method 2a or 2b.   Your project could well do the same.

**Comment by petervwyatt** [comment]
Correction: ISO charges everyone for their standards, including those involved. But if you are involved then you get to change what is in a standard (awesome!) and you get intermediate work-in-progress drafts (but not the final standard) for free as part of your involvement.

**Comment by mkl-public** [comment]
> one can participate in the development of the standard at little to no charge 
There might be countries where "little to no charge" applies, but last time I asked it was 1000€ per year where I come from. An effective counter-incentive.

**Comment by pietermarsman** [comment]
Standardisation and charging for your services are contradictory IMHO.

**Comment by petervwyatt** [comment]
ISO 32000-2:2020 and resolved errata are now available at no cost thanks to generous sponsors!
https://pdfa.org/sponsored-standards/
