### ISSUE TITLE
Does `HTO` on the ExtGState propagate into Form XObjs?

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#137]
Let us consider a simple content stream as shown below. Where /GS0 is a ExtGState dictionary specifying HTO as [1, 1]. While /Fm0 is a form xObject.
 
1 0 0 1 100 100 cm
/GS0 gs 
1 0 0 1 200 200 cm
/Fm0 do
 
We now further assume that /Fm0 has only 2 graphic objects in its stream as shown below.
 
q
%% Fill-1
1 0 0 0 k 
1 0 0 1 10 10 cm
0 0 20 20 re
f
Q
q
%% Fill-2
0 1 0 0  k
1 0 0 1 100 100 cm
0 0 5 5 re
f
Q
 
Assuming that HTO is inherited as with other values of ExtGState, the converted HTO values would be [311, 311] for Fill-1 and [401, 401] for Fill-2.
 
Correct?

**Comment by petervwyatt** [comment]
@MPBailey ?

**Comment by MPBailey** [comment]
Yes, HTO should be inherited by the form XObjects. That’s in line with the use case that triggered the request to add it: something like step & repeat labels where a label instance is specified as a form, but where that form will often have child forms as well, and where the goal is to ensure that the halftone is positioned in the same place relative to each label. As a general rule graphics state is inherited into XObjects anyway. And Table 57 says “Although the numbers are specified in the current coordinate system, changes to the current coordinate system (for example as a result of invocation of a form XObject) do not move the halftone origin relative to the underlying device coordinate system” confirming inheritance.

I’m not completely sure what you’re asking about converted HTO values, though. If you’re assuming that the form Matrix is [ 1 0 0 1 0 0 ] then I agree with your numbers if I’m following the question as you intended.

**Comment by MPBailey** [comment]
In more detail. In the form user space for the first fill the halftone origin would be -209 -209. It’s set at 101 101 relative to the default user space, the subsequent 200 200 and then 10 10 translations mean that the current user space origin when the fill is called is at 310 310. So the origin in that user space is -209 -209.

Does that help?

**Comment by s-khurana** [comment]
Thanks @MPBailey for the explanation. Just to confirm our understanding, I have a couple of follow-up question as well. Before proceeding to the questions, let me introduce another example.

Let us consider another simple content stream as shown below. Where /GS0 is a ExtGState dictionary specifying HTO as [1, 1]. While /Fm1 and /Fm2 are form xObjects.
 
```
1 0 0 1 100 100 cm
/GS0 gs 
1 0 0 1 200 200 cm
/Fm1 do
1 0 0 1 200 200 cm
/Fm2 do
```

We now further assume that /Fm1 has only 2 graphic objects in its stream as shown below.

```
q
%% Fill-3
1 0 0 0 k 
10 10 20 20 re
f
Q
q
%% Fill-4
0 1 0 0  k
100 100 5 5 re
f
Q
```

While the /Fm2 has 4 graphic objects in its stream as shown below. Where /Im0 and/Im1 are image xObjects.

```
q
%% Fill-5
1 0 0 0 k 
10 10 20 20 re
f
Q
q
%% Fill-6
0 1 0 0  k
100 100 5 5 re
f
Q
q
%% Image-1
10 0 0 10 150 150 cm
/Im0 do
Q
q
%% Image-2
10 0 0 10 250 250 cm
/Im1 do
Q
```

Now let's discuss a couple of questions involving the above example.

**Question 1.**
Observe that /Fm1 is almost identical to /Fm0 described earlier by lrosenthol, as both will result in identical graphic artwork. However, when printed, both /Fm0 and /Fm1 will result in different pixel outputs. 

This difference in output is because /Fm0 uses CTM in its stream thus updating the current coordinate space for both fill objects. Due to the provided CTM along with fills (Fill-1 and Fill-2), HTO for both fills is computed independently. Resulting in different HTO values on device while the relative distance to HTO remains the same for both fills.

Whereas the /Fm1 defines both fills in the same coordinate space, without any usage of CTMs. Hence, the HTO computation for both fills (Fill-3 and Fill-4) remains identical and results in the same HTO on device for both of the fills.

Is my understanding and its corresponding reasoning correct? 

**Question 2.**
From the initial example, as described earlier by lrosenthol, we understood that all CTMs applicable on fills should be taken into account while computing HTO values, even they are contained within a form xObject. 

Does this understanding holds true for all PDF constructs (including image xObjects)? 

For illustration, we can consider the example noted in this comment itself, where we have two image xObjects contained in the form /Fm2's content stream. So, assuming that the user-space to device matrix is [ 1 0 0 1 0 0] for the above noted PDF snippet. Then, by considering all the CTMs applicable on images, we get the device HTO values for image xObjects (Image-1 and Image-2) from /Fm2 as [650, 650] and [750, 750] respectively. 

Is this computation of HTO along images correct?

Please let us know your thoughts.

**Comment by bertvankerckhove** [comment]
I think there is a bit of confusion about HTO parameter values in an ExtGstate dictionary and the HTO value that is part of the graphics state and is subject to inheritance by nested constructions.

HTO in an ExtGState dictionary:
- when an ExtGState dictionary is 'processed' because of a gs operator, it specifies changes to the current graphics state.  For HTO this means that the HTO parameter values, which are expressed in local coordinates, must be transformed to device coordinates - only at the time this gs operator is executed.

HTO in the graphics state:
- this HTO value is always in device coordinates and since inheriting them in nested constructions does not change the graphics state, the physical location of the HTO on the device is not influenced at all

By consequence there needs not be any HTO computations or transformations when rendering subsequent graphical objects, when changing CTM or processing nested forms or images.  Only at the time of changing the HTO with a ExtGState 'command'.

**Comment by MPBailey** [comment]
The existing (2020) text says:

> "Although the numbers are specified in the current coordinate system, changes to the current coordinate system (for example as a result of invocation of a form XObject) do not move the halftone origin relative to the underlying device coordinate system."

In other words the specific use case discussed in this issue is already addressed in that statement.  My personal view is that the current text is fine and does not need changing. But obviously some smart people are having trouble with it; perhaps somebody would like to suggest why, and how we might rectify that?

**Comment by petervwyatt** [comment]
PDF TWG agree the current wording in Table 57 is sufficiently clear.
Closing no fix.
