### ISSUE TITLE
definition of N entry in 3D nodes dictionary ambiguous in case of RichMedia 3D annotations

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#156]
**N** entry in 3D nodes dictionary (Table 323) specifies node ID, to which these node properties (transformation matrix, opacity, etc) should be applied. 

The format of node ID depends on the embedded 3D model formal and is different for U3D and PRC, as specified now in the definition of **N** entry. However, this definition assumes the presence of the 3D stream (Table 311), which does not exist in case of 3D model embedded into PDF as a RichMedia annotation.

In case of RichMedia the 3D model is embedded not as a 3D stream, but as an asset referenced from the RichMediaContent dictionary (Table 341). The only available mechanism today to determine the **Subtype** of an asset (=file format of the embedded 3D model) is a **Subtype** entry in the embedded file dictionary, which is optional at the moment. If this **Subtype** entry is not present in the embedded 3D asset, the only other mechanism available to distinguish between U3D and PRC is to read the header of the embedded file and use magic number technique.

One possible way to fix this issue would be:
 - require MIME type defined (via **Subtype** entry of the embedded file) for all assets referenced by the RichMediaContent dictionary (this would be useful not only for RichMedia 3D annotations, but also for Audio and Video ones). In case of embedded U3D and PRC this is related to #155 
 - update the definition of **N** entry in Table 323 to use either **Subtype** entry in the 3D steam dictionary or a **Subtype** entry of the embedded file dictionary for the embedded 3D asset to determine the format of the 3D model

**Comment by petervwyatt** [comment]
This has a direct impact on [ISO/DTS 24064 (STEP)](https://www.pdfa.org/iso-status/#_Toc35944568) since that extension relies on RichMedia annots for STEP support and thus the **Subtype** key won't exist. See subclause 4.3 in ISO/DTS 24064.

So this issue should be resolved with urgency so that ISO/DTS 24064 can know what to do! @philspreier

**Comment by petervwyatt** [comment]
PDF TWG agree to make MIME media type a "should" for 3D assets only, with an informative note implying that this applies to STEP (where it should have been a "shall")

**Comment by petervwyatt** [comment]
Table 44 Embedded file stream dictionary, **Subtype** current wording: 
>_(Optional, required in the case of an embedded file stream used as an associated file)_ ...

Table 44 Embedded file stream dictionary, **Subtype** proposed new wording:
>_(Optional, required in the case of an embedded file stream used as an associated file (see 14.13 "Associated files") or an asset of a RichMedia annotation (see "13.7 Rich media"))_ ...


In addition, "Table 323 Entries in a 3D node dictionary" for **N** needs major rework since it only describes 3D annotations and not RichMedia annotations as noted by this issue. Here at least is the logic laid out in a tabular form:

| 3D model format | When using a 3D annotation | When using a RichMedia annotation |
| --- | --- | --- |
| U3D | The **Subtype** of the corresponding 3D Stream shall be _U3D_ (see Table 311) then the value of the **N** entry shall correspond to the field Node block name, specified in the Universal 3D file format. | The **Subtype** of the corresponding Embedded File Specification dictionary (see Table 44) shall be the registered IANA MIME media type for U3D "model/u3d" (when expressed as a name is _model#2Fu3d_) then the value of the **N** entry shall correspond to the field Node block name, specified in the Universal 3D file format (ECMA-363). |
| PRC | The **Subtype** of the corresponding 3D Stream shall be _PRC_ (see Table 311), then the value of the **N** entry shall be the Unique Identifier (UUID) as specified in ISO 14739-1. |  The **Subtype** of the corresponding Embedded File Specification dictionary (see Table 44) shall be the registered IANA MIME media type for PRC "model/prc" (when expressed as a name is _model#2Fprc_), then the value of the **N** entry shall be the Unique Identifier (UUID) as specified in ISO 14739-1. |
| STEP (_see ISO/TS 24064_) | Prohibited | The **Subtype** of the corresponding Embedded File Specification dictionary (see Table 44) shall be a registered IANA MIME media type for STEP listed under the "model" registry (see https://www.iana.org/assignments/media-types/media-types.xhtml#model), then the value of the **N** entry shall be the unique identifier (UUID), specified in the STEP AP 242 stream.  |

This table could be added to ISO 32000-2:2020 below Table 323, as new Table 323-A, with the description of **N** reducing to: 

> (_Required_) The name of the node being described by the node dictionary. All names in the node dictionary shall be unique. Interpretation of this entry shall depend upon the 3D format as defined in Table 323-A below.
NOTE 1 When comparing this entry to node names, PDF processors will need to translate between the PDF text encoding used by PDF and the character encoding specified in the stream containing the 3D model.

**Comment by petervwyatt** [comment]
Feedback on the above is requested before this errata is closed.

**Comment by petervwyatt** [comment]
PDF TWG recommend limiting STEP MIME media types to just the 4 that are currently defined to avoid future creep.

**Comment by petervwyatt** [comment]
PDF TWG with above change
