### ISSUE TITLE
A few clean-ups to ICC spec references

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#181]
The intro to 32000-2:2020 says “ISO 15076-1:2010 dated reference for ICC.1 can be supplemented by the Errata list and approved revisions available from the ICC website (http://color.org/icc_specs2.xalter) – see 8.6.5.5, "ICCBased colour spaces"”, but:

- There is no reference to ICC.1 in either normative references or in the bibliography, except in the name of 15076-1 in normative references. Neither is there anything under terms and definitions or notations to establish “ICC.1” as an indirection to anything.

- 7.4.9 (JPXDecode filter) says images may use “An input ICC profile of any sort defined by ICC.1.” This is normative text, so surely ICC.1 should be in normative references … or this reference needs replacing with 15076.

- 8.6.5.5 (ICCBased colour spaces) uses dated references in Table 66 and the bullet points under it. Specifically the row in the table for PDF 2.0 says it supports “ICC.1:2010 (ISO 15076-1:2010)”, and the bullets say that “A PDF reader shall support ICC.1:2010” and “A PDF writer should use ICC 1:2010 profiles”. These requirements seem to assume that the line in the table establishes a synonym for ICC.1 that can be used in the bullets below it. I don’t see that it does. So the same options for correction as for JPXDecode above would apply.

The simplest solution for those last two might be to define “ICC.1:2010” as a synonym for 15076-1:2010 in terms and definitions.

But that still doesn’t deliver the claim in the intro about approved revisions from the ICC website. I’m not sure how to do that, unless that is rolled into the terms & definitions entry?

And in all of this I haven’t touched on the long discussion in the last JWG7 call about whether there should be a dated revision of 15076-1 or whether an amendment would be better!

**Comment by petervwyatt** [comment]
There is also T&D 3.31 "ICC profile": 
> ISO 15076-1:2010 or any of the ICC.1 specifications

and T&D 3.32 "ICC Specification": 
> cross-platform profile format for the creation and interpretation of colour data and means of reference to ISO 15076-1:2010 or any of the ICC.1 specifications

so every use of either term throughout ISO 32000-2 needs to be directly replaced inline with the appropriate expanded definition. That is how the intro covers itself, through the trickery of the rules of interpreting ISO standards and without wholesale bulk changes to wording that has existed for quite a while.

**Comment by petervwyatt** [comment]
So I think there is no change that is technically required here under ISO rules because of the formal T&Ds... but that is not to say additional informative notes might be useful.  
@MPBailey?

**Comment by MPBailey** [comment]
I'm still uncomfortable with the undefned reference to "ICC.1".

Almost all of the references to ICC.1 in the body of the standard (after section 3, and excluding Table 66" could be replaced with "ICC specification", as already defined in T&D.

The statement in the introduction about errata etc could be actually implemented by extending 3.32 to say:

> ICC specification
> cross-platform profile format for the creation and interpretation of colour data and means of reference to ISO 15076-1:2010 or any of the ICC.1 specifications, _supplemented by the Errata list and approved revisions available from the ICC website (http://color.org/icc_specs2.xalter)_
>

But that still leaves a missing reference for "ICC.1" because it's used in normative text. Just for info, I did a Google search for "ICC.1" and nothing on colour profiles popped in the first couple of pages, so some assistance for non-colour-savvy developers wouldmake sense.

I'd suggest adding an undated reference to ICC.1 in Normative References, but the title changes with each version, so I'm not sure how that could/should be structured. 

On the other hand, Table 66 implies that there should be normative references to each of the individual ICC.1 standards anyway.

**Comment by petervwyatt** [comment]
As discussed during the last PDF TWG, @MPBailey, @lrosenthol and myself took this offline and discussed in detail. Our conclusion is as follows (for general PDF!):

* Table 66 is really a history lesson of what ICC versions were current when past PDF specs were first released.
* we CANNOT delete Table 66 as this will renumber most Tables in 32K, but we can replace its content or leave as "Table intentionally blank"
* ICC profiles all use major and minor version numbers in their profile header - the industry already uses terms such as v2.x, v4.x and v5.x (iccMAX) profiles. Don't confuse ICC profile header versions with ICC spec versions as these were different in the early days!
* we are NOT discussing v5 (iccMAX) profiles for PDF - that is later discussion for ISO TC 130 WG 2. 
* ICC profiles with the same major version numbers are compatible (as so stated in all ICC specs)
* thus PDF only needs to refer to the latest v2 and latest v4 specs, since these will include everything needed for all minor versions under that major version
* for v4 we recommend changing 32K-2 to an UNDATED revision of ISO 15076-1, since we know a dated revision is in progress (ISO 15076-1:202x)
* for v2, we need to refer "Specification ICC.1:2001-04 File Format for Color Profiles (v2.4.0)" dated April 2001 which we believe is the latest v2.x.x spec. I have reached out to the ICC for them to make this appropriately available via a "nicely referenceable" means... 
* we also checked the various ISO subsets PDF/X, PDF/VT, PDF/A, and PDF/R for other mentions of ICC version, ICC specs, ISO 15076, etc. Some minor maintenance is required for some of these and appropriate communication to the relevant WGs is in progress. Obviously subsets can further restrict things if they see fit.

There are various spots in ISO 32000-2:2020 to tidy up: the Normative Refs, the T&D for ICC profile, the Intro, Table 66, etc. 

Since we have Table 66 needing a replacement (so as not to renumber every other table) I propose to replace it with a Table that lists the ICC profile header major version and the appropriate normatively reference documents, with a statement referencing that table along the lines of "ICC profiles in PDF shall have ICC profile header major versions as shown in Table 66" (TBD wordsmith). People already know of this table and this new content is the "modern equivalent" of what was there...

**Comment by petervwyatt** [comment]
https://www.color.org/specification/ICC.1-2001-04.pdf 
https://www.color.org/specification/ICC.1-2022-05.pdf 
https://www.color.org/specification/ICC.2-2019.pdf

**Comment by petervwyatt** [comment]
PDF TWG agree.
Follow up with PDF/R, TC 130 and WG5.
