### ISSUE TITLE
Why is Font Descriptor Descent strictly negative? Why is zero Descent not permitted?

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#190]
Table 120 for Font Descriptors defines **Descent** as:
> (_Required, except for Type 3 fonts_) The maximum depth below the baseline reached by glyphs in this font. The value shall be a negative number.

Examining millions of PDFs shows that **Descent** 0 (zero) is extremely common even tho' the negative requirement was originally stated back in Adobe PDF 1.0.  So why is **Descent** strictly negatively (i.e. the smallest valid value for Descent is thus -1) and zero not allowed? Not all glyph sets or typefaces have descenders that project _below_ the baseline...

PS. I am ignoring the sizable collection of invalid PDFs that have **Descent** with very large _positive_ values!

**Comment by MatthiasValvekens** [comment]
Well, whether "negative" means `<0` or `≤0` can be somewhat regional. Some people would call these "strictly negative" and "negative", while others would say "negative" and "nonpositive".

I'm not sure if ISO has guidance on  this specific issue, but if we want to be absolutely unambiguous, we should say "The value shall be a number less than or equal to zero".

**Comment by bdoubrov** [comment]
The current wording of the OpenType technology is even less strict (https://docs.microsoft.com/en-us/typography/opentype/spec/os2#uswindescent):

> the usWinDescent value treats distances below the baseline as positive values; thus, usWinDescent is usually a positive value, while sTypoDescender and hhea.descender are usually negative.

I think the main idea is that the **Descent** value should be negative if the font glyphs go below the baseline. So this is not just the absolute distance, but the directional one, where "below" means negative.

**Comment by bdoubrov** [comment]
As a side note, some implementations do use Ascent and Descent to calculate the visual highlight of the selected text. While this is definitely implementation dependent (PDF Spec does not mandate how to visualize the text selection), having the correct values of these two fields that match the corresponding properties of the embedded font program is highly recommended.

**Comment by MPBailey** [comment]
32000-2 uses "non-negative" for "0 or greater" (plus one of "nonnegative"); I could not find any instances of "non-positive" for "0 or less".

There are some statements that clearly imply 'negative' does not include zero, such as "may be either positive or negative but shall not be zero." There are also a number of instances where things would break if "negative" were interpreted as "0 or less". Let's not go there.

So I'd suggest that the text for Descent be replaced by "shall be zero or a negative number".

BTW - the nearest valid value to zero for Descent is not currently -1 because it's a number rather than an integer, so it's -0.000...0001. Close enough to zero for all practical purposes, which is why I'd be very relaxed about allowing 0.

**Comment by petervwyatt** [comment]
PDF TWG agree - also add informative note like Boris' comment above
