### ISSUE TITLE
[Found in 1.7] The first operand for `Tf` should be specified to be a name object

### ISSUE THREAD

**Issue by TonalidadeHidrica** [pdf-association/pdf-issues#207]
Fonud this issue in PDF 1.7 spec (ISO 32000-1:2008).  It may have been corrected in the latest PDF 2.0 spec (ISO 32000-2:2020 = PDF 2.0), which I cannot check.

**Describe the bug**
9.3.1 General, Table 105 – Text state operators
> font shall be the name of a font resource in the Font subdictionary of the current resource dictionary

I'm not sure, but "the name" should be explictly stating "name object", shouldn't it?

**Comment by petervwyatt** [comment]
No - that wouldn't be correct as that might be misinterpreted as implying an indirect reference to a name object. If anything it might be more along the lines of: ... _the value of the name object of a named font resource_... but that is not how the PDF specs have ever been worded (since the same logic would then also apply to every integer or real as they are objects in the same sense). Furthermore, clause 7.8.3 and many other places would then need a lot of rewording to be kept aligned.

We appreciate your contributions but please realise that ISO 32000-2:2020 has had over 12 years of input and review in the vendor-neutral consensus-based ISO working groups by many subject matter experts so many of these issues have already been discussed. You will also learn a great deal and have a far better interoperable implementation if you can use the updated specification, especially in the area of resource inheritance!
