### ISSUE TITLE
Table 263 incorrectly describes signature Reference as a dictionary when it is an array

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#218]
"Table 263 — Entries in a permissions dictionary" says "_... This dictionary shall contain a **Reference** entry that shall be a signature reference dictionary (see "Table 255 — Entries in a signature dictionary") that has a **DocMDP** transform method (see 12.8.2.2, "DocMDP") and corresponding transform parameters._"

However "Table 255 — Entries in a signature dictionary" defines **Reference** to be an array (only) so this should really say:
> This dictionary shall contain a **Reference** entry that shall be an array with an entry that is a signature reference dictionary...

I'm unsure if this requirement applies only to an array of length 1 or length _N_, all array elements, etc.
@MatthiasValvekens? @lrosenthol?

**Comment by MatthiasValvekens** [comment]
I agree w.r.t. the error in the wording in Table 263.

-------

Regarding the length of the **Reference** array:

It's my understanding that you could have a certification signature with a **DocMDP** reference dictionary (or rather, a **Reference** dictionary with **DocMDP** **TransformParams**) setting the DocMDP level to 2 (=form field editing allowed), and at the same time a **FieldMDP** reference dictionary limiting the form fields fields that can actually be edited. That'd leave you with a reference array of length two.

This would conform to the spec IIRC, but I admittedly don't know how different implementations would deal with this. It's been a long time since I last checked.


------

Granted, I suspect that the _original_ reason why **Reference** is defined as an array has more to do with those object-based signatures that never made it into "ISO PDF". Having **Reference** be an array would then allow the user to point to multiple nodes in the object graph to be digested, for example. But of course @lrosenthol is in a better position to comment on that.

**Comment by petervwyatt** [comment]
> ... .but why not just shorten it to this?

My original thinking was so that an empty array isn't valid... but I guess the additional requirement "_... that has a DocMDP transform method (see 12.8.2.2, "DocMDP") and corresponding transform parameters._" avoids that.

**Comment by MatthiasValvekens** [comment]
That's what I was thinking as well. But I now see that my edited version doesn't really read as well in context, given the rest of the sentence. Maybe this variation on your original proposal is even less ambiguous:

> This dictionary shall contain a **Reference** entry that shall be an array with at least one entry, exactly one of which is a signature reference dictionary that has a **DocMDP** transform method (see 12.8.2.2, "DocMDP") and corresponding transform parameters.

Of course whether or not this is a good idea depends on whether the use case for DocMDP + FieldMDP from my previous comment is actually permissible.

**Comment by MatthiasValvekens** [comment]
By the way, #61  shouldn't impact the resolution of this discussion (since it's about approval signatures), but the context is perhaps relevant.

**Comment by petervwyatt** [comment]
PDF TWG agree
