### ISSUE TITLE
Extension level numbers increasing over time

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#239]
Table 49 of ISO 32000-2:2020 says: "If the developer introduces more than one extension to a given BaseVersion the extension level numbers assigned by that developer SHOULD increase over time."

This means that ISO 32003 SHOULD be published before ISO 32004 (both probably having ISO_ as prefix name). Fortunately, that's a SHOULD, not a SHALL.

I think this dates back to PDF 1.x where there could be only one extension per developer and ADBE extensions where each extension included all previous extensions.

Now that arrays are allowed in the extenions dictionary, that restrictions could be removed.

(The "bug" label wasn't intended, sorry.)

**Comment by MatthiasValvekens** [comment]
I think the `bug` label is appropriate, though ;). Regardless of publication schedule, the numbering for ISO extensions clearly has nothing to do with time, so we should definitely reword that provision so that it doesn't apply to array-valued extensions.

**Comment by petervwyatt** [comment]
I think the SHOULD recommendation should stay so probably the easiest (non-normative) fix is to add an informative note to state that ISO extensions under the developer prefix ISO_ use the ISO document number for the extension level numbers.

**Comment by petervwyatt** [comment]
At ISO we intentionally deviated from the existing rules as experts in ISO committees have no control over ISO processes, document identifications, document numbers, release dates, etc. So for ISO extensions, this number is a document identifier reference, not a document "level" - but we could certainly do a better job of explaining to the world how this is being used within ISO.

So I think "normal" vendors should (_not shall_!) still try and use incrementing versioning as has always been specified since they can control their choices to meet the spec (cf. the Adobe Extension Levels to ISO 32000-1:2008) whereas in ISO such flexibility is not possible.

**Comment by petervwyatt** [comment]
7.12.5:
The value of the ExtensionLevel entry shall be an integer, which shall be interpreted with respect to
the BaseVersion value. If a developer has released multiple extensions against the same BaseVersion
value, they shall be ordered over time and the ExtensionLevel numbers shall be a monotonically
increasing sequence over time.

Table 49, ExtensionLevel:
(Required; shall be a direct object) An integer defined by the developer to denote the extension being used. If the developer introduces more than one extension to a given BaseVersion the extension level numbers assigned by
that developer should increase over time.

Reword 7.12.5 last sentence:
If a developer has released multiple extensions against the same BaseVersion value, they should be ordered over time and the ExtensionLevel numbers should increase over time.
 
 PDF TWG agree
