### ISSUE TITLE
Length entry in cross-reference streams should be a direct object

### ISSUE THREAD

**Issue by bdoubrov** [pdf-association/pdf-issues#246]
Currently section 7.5.8.2 Cross-reference stream dictionary imposes several restrictions on which entries shall be direct objects. In particular, if the cross-reference stream stream is compressed then **Filter** and **DecodeParms** entries in "Table 5: Entries common to all stream dictionaries" shall also be direct objects.

But I think **Length** entry is equally important for parsers and shall also be a direct object for cross-reference streams. And this is independent of whether the stream is encoded or not.

**Comment by lrosenthol** [comment]
Length is useful as an indirect object on a stream - any stream - when creating on the fly and you don't know the length till the operation is complete.

**Comment by MatthiasValvekens** [comment]
I agree in general, but if the stream is a cross-reference stream, how do you dereference the length entry? It seems (to me, at least) that it's functionally required to be direct. If so, the spec should probably say so explicitly.

**Comment by petervwyatt** [comment]
See also Errata #114 which is now also approved by ISO WG8 and will be included in Amendment 1: https://pdf-issues.pdfa.org/32000-2-2020/clause07.html#H7.5.7:

"_Any entry's value in an **ObjStm** dictionary shall be either a direct object or an indirect uncompressed object_."

so I believe we already solved this.

**Comment by MatthiasValvekens** [comment]
But that's for object streams, not xref streams, right? It's certainly related, though.

**Comment by petervwyatt** [comment]
Sorry - you are correct that this only solves for object streams.  

But I disagree about "you don't know how to dereference _any_ objects yet" since cross-reference streams apply to hybrid reference PDFs and they form a linked-list using **Prev** so the spec should not assume any particular algorithm about processing so under a defined set of circumstances and choice of specific algorithm indirectness of stream extent dictionary keys is theoretically supportable... 

I think the question is whether we try and get technically precise and specify exactly which, when and how stream extent dictionary entries in Table 5 can be indirect for cross-reference streams as theoretically any of those entries will be needed for decoding the cross-reference stream. Or we just extend the wording which prohibits all entries in Table 17 from being indirect to also include Table 5. The requirement for direct objects all needs to cascade down through all arrays and dictionaries in Table 5 (the keys are more complex than Table 17) - the only catch is that **F** can eventually refer to streams, but no one should be using **F** on a cross-reference stream so it is probably easier to outright prohibit **F** that rather than attempt to solve. 

My preference is for the latter as it is far simpler and why encourage undue complexity that doesn't exist in the real world?!

**Comment by MatthiasValvekens** [comment]
> But I disagree about "you don't know how to dereference any objects yet" since cross-reference streams apply to hybrid reference PDFs and they form a linked-list using Prev so the spec should not assume any particular algorithm about processing so under a defined set of circumstances and choice of specific algorithm indirectness of stream extent dictionary keys is theoretically supportable...

OK, fair enough, but I think it's fair to say that all bets are off at that point as far as interoperability is concerned ;). So perhaps we can agree that "you don't know how to _unambiguously_ dereference any objects yet" is a more correct statement?

> [...]. Or we just extend the wording which prohibits all entries in Table 17 from being indirect to also include Table 5. The requirement for direct objects all needs to cascade down through all arrays and dictionaries in Table 5 (the keys are more complex than Table 17) - the only catch is that F can eventually refer to streams, but no one should be using F on a cross-reference stream so it is probably easier to outright prohibit F that rather than attempt to solve.

On balance, I would be in favour of specifying that all entries in Table 5 must be direct if used in an xref stream extent dictionary, and that the F key is forbidden in that context as well. It removes ambiguity in xref dereferencing, and doesn't really get in the way of any legitimate use cases of cross-reference streams as far as I can tell.

**Comment by petervwyatt** [comment]
Suggested proposed solution for last sentence of first bullet. Currently states:

> If the stream is encoded, the **Filter** and **DecodeParms** entries in "Table 5 — Entries common to all stream dictionaries" shall also be direct objects.

Reword to:
> The values of all entries shown in "Table 5 — Entries common to all stream dictionaries" shall also be direct objects.  For arrays, all array elements shall be direct objects and for dictionaries, all key values shall be direct objects as well. The **F** entry defined in Table 5 shall not be used.

**Comment by petervwyatt** [comment]
PDF TWG agree.
