### ISSUE TITLE
Expiry of TimeStampToken (ISO 32000-2:2020 12.8.5.3 vs. RFC 3161)

### ISSUE THREAD

**Issue by a20dev** [pdf-association/pdf-issues#252]
21.8.5.3 of ISO 32000-2:2020 implies that a TimeStampToken expires when its signing certificate expires:

"A timestamp token present either in a signature timestamp attribute or in a document timestamp
dictionary may expire due to the expiry of its certificate [...]"

However, according to RFC 3161 (a normative reference for ISO 32000-2), a TimeStampToken never expires. Appendix B reads

"The date/time indicated by the TSA MUST be within the validity period of the signer's certificate."

There are no other requirements related to the validity period of the signing certificate. It's even not possible to revoke a TimeStampToken by revoking the signing certificate after generation of the TimeStampToken:

"Should the certificate be revoked, then the date/time of revocation shall be later than the date/time indicated by the TSA."

Was that implied definition of expiry of TimeStampTokens made up for ISO 32000-2 or is there some normative reference I' don't know about? Or is that implied definition a mistake in ISO 32000-2?

**Comment by MatthiasValvekens** [comment]
Hmm, I think you're reading a little too far into RFC 3161 to make those inferences. Perhaps unfortunately, the steps of the validation algorithm in RFC 3161, Appendix B are formulated as if they were normative requirements on the timestamp tokens, but actually they're validator requirements. (To be even more pedantic: since Appendix B is an example annex, it's even debatable whether its contents are normative at all, but that's beside the point.)

In other words, when the text says "The date/time indicated by the TSA MUST be within the validity period of the signer's certificate.", the intended meaning in that context is probably more like "The validator _shall verify that_ the date/time indicated by the TSA is contained within the validity period of the signer's certificate.".


In practice, TSA certificates do expire (and can be revoked as well). For example, ETSI standards even outside the PDF context discuss at length what to do to establish trust in potentially expired timestamp records.

**Comment by a20dev** [comment]
ETSI TS 119 102-1 seems to be the relevant document, but it's neither a normative reference for ISO 32000-2 nor for the ETSI EN 31 referenced by ISO 32000-2.

Expiry of a TimeStampToken (and therefore of a DTS) depends on validation policy. If the chain model is used, TimeStampTokens won't expire with their signing certificate (still subject to further requirements of the validation policy). If the shell model is used, they will expire with their signing certificate.

Therefore, ISO 32000-2 reads ""A timestamp token present either in a signature timestamp attribute or in a document timestamp dictionary MAY expire due to the expiry of its certificate [...]" rather than ""A timestamp token present either in a signature timestamp attribute or in a document timestamp dictionary WILL expire due to the expiry of its certificate [...]".

**Comment by MatthiasValvekens** [comment]
> ETSI TS 119 102-1 seems to be the relevant document

Ironically, that reference is also a bit outdated. I believe ETSI EN 319 102-1 is the most recently updated one. But you're right, this entire discussion is mostly out of scope for ISO 32000-2, and arguably also for RFC 3161, so I don't think there's a contradiction.

However, the passage you cite was more or less copied from (a previous version of) the PAdES spec, if I recall correctly (@lrosenthol can probably be more precise).

>  If the chain model is used, TimeStampTokens won't expire with their signing certificate (still subject to further requirements of the validation policy). If the shell model is used, they will expire with their signing certificate.

Granted, my experience with the chain model is limited, but I'm not sure this is accurate... My understanding is that in the chain model, one still needs to _establish_ that a signature was produced within the validity window of the signer's certificate before treating it as valid. Either way, since time stamp tokens are also signatures, that means there are (roughly) two cases:

 - The TSA certificate can still be validated at the current time => OK
 - The TSA certificate is no longer valid/has been revoked/whatever => we need some other piece of evidence to prove that the timestamp was generated during the validity window (e.g. another timestamp, some assertion from a trusted archive, etc...)

AFAIK the difference between the chain and shell model would mostly show up in the validation of the TSA cert in this scenario, not the actual timestamp validation.

**Comment by a20dev** [comment]
The verification time doesn't matter for the chain model, therefore signatures (and TimeStampTokens) don't expire when using the chain model.

Note that national law for at least one country specified usage of the chain model for validating signatures.

**Comment by MatthiasValvekens** [comment]
Again, I'm far from an expert on how the chain model is used in practice (I'm aware that it's mandatory in Germany), but that sounds like an oversimplification to me. For example, EN 319 102-1 still contains provisions specific to the chain model in its section on LTA validation (e.g. in the section on the "validation time sliding process"). None of that would be necessary if validation time simply didn't matter _at all_ in the chain model, no? Or is there something I'm misunderstanding?

If I'm wrong about this (which is certainly possible), could you perhaps provide a reference stating that timestamps are valid indefinitely in the chain model? I'd like to learn why that's the case.


Either way, since RFC 3161 doesn't really normatively specify a particular validation model, I still don't think there's any contradiction to fix in ISO 32000-2, or is there? :)

**Comment by lrosenthol** [comment]
Agree with @MatthiasValvekens - nothing to change in 32K...

**Comment by petervwyatt** [comment]
PDF TWG agree to no fix.
