### ISSUE TITLE
DPart DPM and Metadata keys have seemingly overlapping descriptions

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#290]
Table 409 - Entries in a DPart dictionary, has both a **DPM** key and a **Metadata** key with seemingly overlapping descriptions:
* **DPM**: If present shall specify a document part metadata dictionary.
* **Metadata**: A metadata stream that shall contain metadata for this document part.  

Some informative information about differences, pros/cons of each, or when to use one vs the other (besides the obvious syntax differences) could be very helpful looking to use DPM

**Comment by DietrichSeggern** [comment]
We currently have:
"Metadata
(Optional; PDF 2.0; shall be an indirect reference) A metadata stream that shall contain metadata for this document part (see 14.3.2, "Metadata streams")."

Proposed new text:
"NOTE A DPart dictionary can in addition or instead of DPM metadata have "regular" metadata streams. DPM will usually take advantage of the hierarchical structure of the DPart tree separating document parts using corresponding metadata fields in each of its instances to enable automated and integrated processing of the document parts. This "regular" metadata streams will on the other hand often be unrelated to other DPart nodes. To support its mission DPM is more open and can be used with all possible metadata syntaxes (14.12.4.2 Document part metadata), metadata as used here has to follow the XMP standard (14.3.2 Metadata streams)."

(I am sure that the wording can be improved, but I believe these are the main points.)

**Comment by lrosenthol** [comment]
I support the concept of the proposal by @DietrichSeggern but agree that the wording needs improvements (and some additional references/links).

**Comment by petervwyatt** [comment]
PDF TWG ask me to rework informative NOTE from @DietrichSeggern for future review

**Comment by petervwyatt** [comment]
Reworked informative NOTE wording for **Metadata** cell in Table 409:

NOTE A **DPart** dictionary can be used in addition to, or instead of, XMP metadata streams (see 14.3.2 Metadata streams). Document part metadata (see 14.12.4.2, "Document part metadata") can take advantage of the hierarchical structure of the **DPart** tree structure (see 14.12.2, "DPart tree structure") by using application-specific metadata fields (encoded as PDF objects) in each instance to enable automated and integrated processing of document parts. On the other hand, XMP metadata streams may be unrelated to other **DPart** nodes but are encoded in according to the XMP specification.
