### ISSUE TITLE
Clarify Table 93 Type 1 Form XObject Resources description

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#292]
At the request of the PDF TWG, this errata is being split out from errata #128 to focus on improvements to wording in Table 93 and the **Resources** entry - specifically the historic discussion and ensuring appropriate normative requirements (file format, processor) and alignment with other changes from errata #128 (Type3 glyph descriptions) and #291 (Linearization).

**Comment by petervwyatt** [comment]
@MPBailey - would you care to suggest some solution now?

**Comment by MPBailey** [comment]
I propose several relatively small changes in the Resources value cell in Table 93, all of which have been discussed a little under #128.
 

- Make the requirement "(Sometimes required; PDF 1.2)". That terminology is used elsewhere already.
- 
- Change para 2 (the discussion of PDF version 1.1) to past tense and remove normative words so that it can be converted into a note (and moved to the end of the cell).
- 
- Para 3 is now incorrect as form XObjects _must_ now be independent, at least as far as resources go. Replace the first sentence of that para with "_In PDF 1.2 and later versions, it is strongly recommended that form XObjects be independent of the content streams in which they appear; from PDF 2.0 this is required._"

Under #128 Peter suggested

> "given that this description of Type 1 Form XObjects gets referenced by annot appearance streams, Type3 glyph descriptions, etc., noting those other features use Type1 Form XObjects for less knowledgeable readers will also help."

I've been unable to find anything in the current text stating that a Type 3 font is represented as form XObjects (it uses contents streams, but they are not identified as XObjects). This is a good thing because our discussions under #128 concluded that the process to find resources should be different for a Type 3 font CharString/Font from that for an XObject.

On the other hand, appearance streams are explicitly described as being form XObjects. But this is already explicitly called out in the bullet list in 8.10.1, and the Appearance Streams clause (12.5.5) includes a cross-reference to Form XObjects (8.10). So I don't think anything more is required here.

**Comment by petervwyatt** [comment]
PDF TWG agree to @MPBailey 3 suggestions above.
