### ISSUE TITLE
In 7.4.3, clarify whether ASCII85Decode can have a newline in the middle of EOD sequence

### ISSUE THREAD

**Issue by johnwhitington** [pdf-association/pdf-issues#293]
Spec says:

"The ASCII base-85 encoding shall use the ASCII characters ! through u ((21h) - (75h)) and the character z (7Ah), with the 2-character sequence ~> (7Eh)(3Eh) as its EOD marker. The ASCII85Decode filter shall ignore all white-space characters (see 7.2, "Lexical conventions")"

Can we have a newline between the ~ and the > or does that mean it's no longer a "2-character sequence"? Depends how one reads it.

Example file available here: https://github.com/qpdf/qpdf/issues/973

It looks reasonable to me: ASCII85Decode is meant for human readability, so putting in newlines every 80 characters is a resonable approach for a PDF writer to take. Depending on the algorithm, this line splitting might happen when the `~>` sequence is already baked in, so a newline may come between the `~` and the `>`.

Recommend appending ", even within the EOD marker." to the final sentence of this paragraph. You can make an argument that there's no ambiguity here, but multiple implementations have been caught out by this, so I think it's worth clarifying by emphasis.

**Comment by petervwyatt** [comment]
My take is that "~>" is a single "token" and must not have whitespace (or an EOL) between these 2 chars, however I'm unsure about whitespace (incl. EOLs) elsewhere.

**Comment by johnwhitington** [comment]
(The distinction drawn between newlines and whitespace in my original comment was a mistake. No such distinction is relevant here.)

My reading of "The ASCII85Decode filter shall ignore all white-space characters (see 7.2, "Lexical conventions")" is that the reference to 7.2 is just about what characters are considered whitespace, not about what the notion of a token is: there is no such notion in compressed stream content discussed in 7.2.

So I think the spec is actually correctly interpreted that all whitespace, even between ~ and > in the EOD sequence is acceptable. Certainly all PDF viewers I have tried allow it. I just think it should be emphasised that it can occur in the EOD sequence, since it can trip up the unwary programmer.

(For reference, the linked file contains an ASCII85Decode stream with a newline between ~ and > in the page content streams. So if the pages display, the PDF viewer is coping with this unexpected newline)

**Comment by johnwhitington** [comment]
For amusement, I ordered a second-hand copy of the original PDF 1.0 reference manual from abebooks. It makes no mention of whitespace at all in the description of ASCII85Decode.

**Comment by petervwyatt** [comment]
Also available online via https://pdfa.org/resource/pdf-specification-index/

**Comment by petervwyatt** [comment]
@lrosenthol - any contributions?

**Comment by MPBailey** [comment]
The ~> is also referred to as an "EOD marker" in the same section, so my instinct would be that it should be atomic. But I agree that the text is not really clear on this point.

FWIW, I scanned though for EOD in the hope of finding salvation elsewhere, and that made me wonder whether 7.3.8.2 (stream extent) needs a tweak as well. That says "(If the stream has a filter, Length shall be the number of bytes of encoded data.) In addition, most filters are defined so that the data shall be self-limiting; that is, they use an encoding scheme in which an explicit end-of-data (EOD) marker delimits the extent of the data.", which doesn't seem 100% clear on whether the delimiting EOD should be included in the value of Length. After all, the EOD is not really part of the encoded data.

I know what most software does on that one, so the obvious fix would be to explicitly state that any EOD marker shall be included in the Length. Probably needs a separate issue?

**Comment by petervwyatt** [comment]
@MPBailey - "Probably needs a separate issue?" = yes please

**Comment by petervwyatt** [comment]
PDF TWG agree that whitespace may occur anywhere including between `~` and `>`.

**Comment by petervwyatt** [comment]
PLRM 3.13.3 "... all whitespace characters ... are ignored"
