### ISSUE TITLE
The requirements for TransferFunctions in the different halftone types should be aligned and cleaned up

### ISSUE THREAD

**Issue by DietrichSeggern** [pdf-association/pdf-issues#310]
Tables 128 (Type 1 halftone dictionaries), 130 (Type 10 halftone dictionaries) and 131 (Type 16 halftone dictionaries) state:

>This entry [the TransferFunction entry] shall be present if the dictionary is a component of a Type 5 halftone (see 10.6.5.6, "Type 5 halftones") and represents either a nonprimary or nonstandard primary colour component (see 10.5, "Transfer functions").

That means that if the halftone dictionary is referenced from a Type 5 halftone dictionary it shall have (under the specified conditions) a TransferFunction entry.

However, Table 132 (for such Type 5 halftone dictionaries) specifies a "Default" entry:

>A halftone that shall be used for any colourant or colour component that does not have an entry of its own. The value shall not be 5. If there are any nonprimary colourants, the default halftone shall have a transfer function.

That seems to suggest that instead of each nonprimary (...) colourant having it's own TransferFunction there may be a Default instead (or maybe that even is the only way to cover such colourants). This needs to be harmonized.

Table 129 (Type 6 halftone dictionaries) has a Note: 

>PDF versions to 1.7 required that this entry be present if the dictionary is a component of a Type 5 halftone (see 10.6.5.6, "Type 5 halftones") and represents either a non-primary or non-standard primary colour component.

Since that provision is still in place in PDF 2.0 the note should probably be removed (or adjusted).

Perhaps the idea was to remove the requirement in Table 132 for Type 5 Halftone dictionaries (which has happened) and to adjust tables 128 through 131 (which has only happened in table 129)? I would support that idea but it would then have to be executed.

If that is the outcome of this, we need to adjust PDF/A-4 and PDF/X-6 (https://github.com/pdf-association/pdfa-twg/issues/13).

If the outcome is that we keep the requirement for nonprimaries we should limit it to spot colors in CMYK (or non standard subtractive color spaces). We would then have to adjust the text above as well as the text in the first bullet after table 132.

After the above we should discuss #311.

**Comment by petervwyatt** [comment]
PDF TWG researched. The change to add the NOTE in Table 129 (Type 6) was introduced after ISO 32000-1:2008 and by ISO 32000-2:2017 - will research ISO comment docs to find out why this change was made.

**Comment by petervwyatt** [comment]
The source comment was "ADDS 651" in ISO WG8 doc N0705. 
![image](https://github.com/pdf-association/pdf-issues/assets/26521615/85f1ca33-a6d6-4cad-aa5e-3e0bb859db02)
but where the right-most column of text spanned 5 pages(!!) with input from @MPBailey 

Here's the full text of just that right-most column - since GH doesn't support colored text the &#x1F534; markers indicates red text in the original:

---
Accepted in principle
Discuss in San Jose in the context of MB:’s Transfer Function content.
I agree that the current text is rather opaque. I was going to say that the text proposed in the comment isn’t far off, but I find myself wondering why the original text talks about ‘altering’ them. Perhaps the thought process was that the consuming system will have a default transfer function set that a PDF file could override (aka ‘alter’). I can’t come up with any other explanation, and the best way to avoid ‘altering’ in that way is to not define them in the PDF. Which brings us back to the proposed replacement. I don’t like “should not make use of them”, but I do like the move from ‘shall’ to ‘should’; ‘shall’ makes no sense when it’s predicated on the intention behind the design. In addition, an absolute prohibition of the use of transfer functions means that you can’t define a halftone for a spot colour, but I guess that you can’t claim to intend to be device-­‐independent if you’re including halftones anyway!
So I propose replacing that sentence with:
“Because transfer functions produce device-­dependent effects, a page description that is intended to be device-independent &#x1F534; should not define a current transfer function in the graphics state, and should only define TransferFunction in any halftone dictionaries as required for nonprimary or nonstandard primary colour components&#x1F534;.”
Alternatively, do both of these:
[if !supportLists]• [endif]Replace the text in the Value column of the TransferFunction line in Table 129 with: “(Optional) A transfer function, which overrides the current transfer function in the graphics state for the same component. The name Identity may be used to specify the identity function. (see 10.4, "Transfer functions") NOTE: PDF versions to 1.7 required that this entry be present if the dictionary is a component of a type 5 halftone (see 10.5.5.6, "Type 5 halftones") and represents either a nonprimary or nonstandard primary colour component.”
[if !supportLists]•
[endif]Replace the sentence in
10.4 with:
“Because transfer functions produce device-­‐ dependent effects, a page description that is intended to be device-­‐ independent should not define a current transfer function in the graphics state, or define TransferFunction in any halftone dictionaries.”

---
 
However there also appears to have been a glitch as "UK 161" in ISO WG8 doc N0723 then said:
![image](https://github.com/pdf-association/pdf-issues/assets/26521615/b14bd620-3952-4bb6-ba50-71d1483c2b0b)

**Comment by MPBailey** [comment]
I'm afraid that my archaeology is hampered slightly by losses when changing computers at some point. I cannot find what I assume must have been am email from me with that long comment in it. That means I can't find any evidence to suggest why I appear to have picked on Table 129 and not mentioned the equivalents for HalftoneType 1, 10 and 16. Sorry.

I cannot now see any reason why Type 6 should be treated differently to the others.

This one should be flagged to the work on a dated revision of PDF/X-6 once all required changes in 32000-2 have been agreed to discuss if there is any desire to continue requiring TransferFunctions in some cases for that.

**Comment by petervwyatt** [comment]
Maybe @bfanning-247 knows where the original correspondence might be...

**Comment by DietrichSeggern** [comment]
Thank you all for your input.

My proposal for changes would then be:

1. Harmonize the entries in Table 128 (Type 1 halftone dictionaries), Table 129 (Type 6 halftone dictionaries), 130 (Type 10 halftone dictionaries) and 131 (Type 16 halftone dictionaries. So that they all use:
`This entry shall be present if the dictionary is a component of a Type 5 halftone (see 10.6.5.6, "Type 5 halftones") and represents either a nonprimary or nonstandard primary colour component (see 10.5, "Transfer functions"). The name Identity may be used to specify the identity function.`

2. In Table 132 (Type 5 halftone dictionaries) add a note to the entry for "any colourant name":
`NOTE As stated for each of the other halftone types the referenced halftone will have a TransferFunction if it represents a nonprimary or nonstandard primary colour component.`

Remark: I also think there is an issue in Table 132 because on the one hand side there is a reference to other halftone dictionaries required for all colorants, but on the other hand there is a Default entry required, that "shall be used for any colourant or colour component that does not have an entry of its own" (which can't exist). But I think we should leave that alone since that all is so old and not (often) used.

3. Add a note to the bullet below that says: "Primary colour components for the standard native device colour spaces (Gray for DeviceGray; Red, Green, and Blue for DeviceRGB; Cyan, Magenta, Yellow, and Black for DeviceCMYK;)."

`NOTE In the context of halftone screening only subtractive colour spaces are relevant which does not apply to DeviceRGB.`

**Comment by MPBailey** [comment]
Thanks Dietrich

I agree with your points 1 and 2, and the suggestion not to mess with Table 132 around Default.

But I've always read the halftones section as being deliberately inclusive on the use of halftones for additive spaces (see the last para of 10.6.2, for instance). I don't really understand why that is (perhaps Leonard can explain the history?), but I feel it would be wrong to add the note you suggest in your point 3 without more debate and more text to support the assertion.

Martin
________________________________

**Comment by petervwyatt** [comment]
I also agree that based on existing wording, halftones are not limited to only subtractive spaces. And I know of at least one implementation that implements them for additive spaces...

**Comment by DietrichSeggern** [comment]
My goal is not to improve anything in these provisions, I just want to make sure that we are in synch with PDF/A and PDF/X.

Background to my proposal is that we in the PDF/A TWG agreed that RGB are not primaries in the context of TransferFunctions in HT5: https://github.com/pdf-association/pdfa-twg/issues/13

There in fact is a clarifying NOTE in PDF/A that limits primaries to CMYK, see Boris' [statement](https://github.com/pdf-association/pdfa-twg/issues/13#issuecomment-1453133070) as a minute to our discussions.

If we want to limit this in PDF/A but not in PDF we can't just use a NOTE there, it would have to be normative.

**Comment by MPBailey** [comment]
I'm not going to take a position on whether limiting TransferFunctions in halftones to only CMYK (and spots) would be useful or not because I just don't know. I do know of physical printers which require to be fed with RGB colour values, and some that actually 'print' in RGB, although I don't recall if any of those require halftoned data (obviously the ones that print in contone do not!).

But 32000-2 discusses RGB "process colours" in a variety of places, such as the bullet after note 4 in 8.6.6.5 (DeviceN colour spaces), backed up by the ColorSpace and Components rows of Table 71. This is made even more explicit in the 1st para of 10.2 (Raster output native colour).

Looking specifically at TransferFunctions, the first bullet in 10.5 (Transfer functions) explicitly discusses transfer functions for an RGB device.

And the last para of 10.6.2 (Halftone screens) discusses applying halftones for additive output spaces, including RGB.

So I'd argue against making any changes in 32000-2, at least without significantly wider discussion.

I have no problems with applying that rule in PDF/A.

Martin
________________________________

**Comment by MPBailey** [comment]
I recommend that we take Dietrich's first two proposals from the 17th of July:

==============

My proposal for changes would then be:

Harmonize the entries in Table 128 (Type 1 halftone dictionaries), Table 129 (Type 6 halftone dictionaries), 130 (Type 10 halftone dictionaries) and 131 (Type 16 halftone dictionaries. So that they all use:

> This entry shall be present if the dictionary is a component of a Type 5 halftone (see 10.6.5.6, "Type 5 halftones") and represents either a nonprimary or nonstandard primary colour component (see 10.5, "Transfer functions"). The name Identity may be used to specify the identity function.

In Table 132 (Type 5 halftone dictionaries) add a note to the entry for "any colourant name":

> NOTE As stated for each of the other halftone types the referenced halftone will have a TransferFunction if it represents a nonprimary or nonstandard primary colour component.

===============

we should then make sure that any further limitations required are made in the current work towards a dated revision of PDF/A-4.

**Comment by petervwyatt** [comment]
PDF TWG would like review by ISO TC 130 WG 2 in their upcoming meetings.

**Comment by petervwyatt** [comment]
AFAIR this was not discussed in ISO TC 130 WG 2 - what would PDF TWG like to do?

**Comment by petervwyatt** [comment]
@petervwyatt will contact TC 130 and ensure this is on the next WG2 agenda (virtual meeting in May 2024)

**Comment by petervwyatt** [comment]
Email sent

**Comment by petervwyatt** [comment]
Discussed in ISO TC 130 WG 2 virtual May meeting today - will wait 2 weeks to allow experts to comment here

**Comment by petervwyatt** [comment]
Time has passed and no comments received here from WG2 experts.

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by petervwyatt** [comment]
Only Table 129 (Type 6) needed the edit. The others already have the precise wording.
