### ISSUE TITLE
is `PrintPageRange` zero-based?

### ISSUE THREAD

**Issue by ousia** [pdf-association/pdf-issues#312]
**Describe the bug**

In the past, I experienced that PDF-1.7 denotes the first page by 0 in `PrintPageRange` (otherwise Acrobat will print page 2 with `/PrintPageRange [ 1 1 ]`), although its spec says that the first page should denoted by 1.

I don’t have access to the newest PDF-2.0 spec, but I was told that the spec hasn’t been modified in this method of page numbering for `PrintPageRange`.

I wonder whether the spec should be fixed to reflect that `PrintPageRange` uses zero-based page numbering, or to explain that PDF-2.0 now uses one-based page numbering (contrary to PDF-1.7).

Many thanks for your help.

**Comment by lrosenthol** [comment]
As noted by @MatthiasValvekens - the current PDF 2.0 specification clearly specifies that page ranges are 1-based.  If any implementations do not behave correctly, they should be fixed...

**Comment by petervwyatt** [comment]
Thanks to our sponsors, the latest ISO 32000-2 is available at no cost for everyone. See https://pdfa.org/sponsored-standards/

Closing as "no fix" as the latest PDF 2.0 specification is entirely clear.

**Comment by JanSlabon** [comment]
I just tested Adobe Acrobat and Reader and FoxIt PhantomPDF: All of them interpret these values as zero-based. I trapped into that issue years ago, too.

### Adobe Acrobat Reader (zero-based):
![grafik](https://github.com/pdf-association/pdf-issues/assets/12390057/0560c4e2-2676-4b91-84c3-a004b420460b)

### Foxit PhantomPDF (zero-based):
![grafik](https://github.com/pdf-association/pdf-issues/assets/12390057/a1522d33-4305-4a63-81f1-fb439834df26)

### Adobe Acrobat Reader (one-based):
![grafik](https://github.com/pdf-association/pdf-issues/assets/12390057/a875aa01-5c46-4910-add2-e10e281153ee)

### Foxit PhantomPDF (one-based):
![grafik](https://github.com/pdf-association/pdf-issues/assets/12390057/107464bc-8fa5-457e-b4ad-7715cf5dbcd8)
(it looks like the numbers are out of range and the entry is ignored completely)


### My test documents:
[ViewerPreferences-one-based.pdf](https://github.com/pdf-association/pdf-issues/files/12047443/ViewerPreferences-one-based.pdf)
[ViewerPreferences-zero-based.pdf](https://github.com/pdf-association/pdf-issues/files/12047444/ViewerPreferences-zero-based.pdf)

It doesn't make sense to keep this as 1-based because it never was nor is implemented in that way.
Also if the document is saved explicitly as PDF 2.0 no application changes its behavior ([ViewerPreferences-zero-based-pdf2.pdf](https://github.com/pdf-association/pdf-issues/files/12047501/ViewerPreferences-zero-based-pdf2.pdf)).

**Comment by JanSlabon** [comment]
Mmmhh... is this really the solution to simply add it to the arlington model? If so, this would be the only implementation that works that way. I'm not aware of any application that really uses these values as 1-based numbers. Each implementation used Acrobat for testing and it never had supported the 1-based way - that's why everybody choosen the 0-based way.

So how should this get fixed if there are no documents on the road that uses the specified implementation but all rely on the behavior of Acrobat?

Is there really any implementor ignoring the behavior of the common applications and sticks to the specification in that case?

**Comment by petervwyatt** [comment]
I don't change Arlington until either ISO TC 171 SC 2 WG8 or the PDF TWG agree with formally changing the spec - it is an exact representation of the spec as it is written.

But since the Arlington data model files (TSVs) are text-based, you can easily do a patch/diff for your own copy of the model as this also allows you to weaken or strengthen any of the spec rules to support your own use cases/needs. Or until the spec catches up.

**Comment by JanSlabon** [comment]
Okay, understood regarding your Arlington update.

Anyhow: There is no integration which had choosen the 1-based way as the big ones all use the 0-based way.

What's the sense to stick to the specifciation which never was implemented that way? I mean it is that simple: If anybody had implemented the 1-based way, the print dialogs (in the common PDF viewer applications) will always show wrong pages. I don't belive that anybody said to hisself: "Doesn't matter. It's the specification.".

Is there a place in the PDF Association to ask how the members have implemented this?

**Comment by petervwyatt** [comment]
Please attend a PDF TWG virtual meeting to discuss.
