### ISSUE TITLE
What does it mean to be "required" and "deprecated" at the same time?

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#317]
Table 25 (Entries common to all crypt filter dictionaries) describes the `Length` field of a crypt filter dictionary as "Required; deprecated in PDF 2.0".  The term "deprecated" usually means that a feature **should not** be used in new code, whereas "required" usually means that the feature **should** be be used.  The combination of the two terms is at least confusing, and possibly contradictory.

Maybe the text should be changed to just read "required", without the "deprecated" add-on?  Or maybe it should read "required before PDF 2.0; deprecated in PDF 2.0"?  Otherwise, it should be clarified for implementors whether software generating PDF 2.0 documents should or should not write a `Length` field.

The attached PDF files show that omitting the Length field is supported in some but not all PDF readers.  "a.pdf" (with `Length` field) works in all readers I tried.  "b.pdf" (without `Length` field) works in Acrobat Reader and the PDF reader built into Google Chrome (on MacOS), but does not work in the MacOS Preview app.

[a.pdf](https://github.com/pdf-association/pdf-issues/files/12279152/a.pdf)
[b.pdf](https://github.com/pdf-association/pdf-issues/files/12279153/b.pdf)

**Comment by petervwyatt** [comment]
ISO 32000-2:2020 clause 3 "Terms & Definitions" has the precise definition of "deprecated" meant for PDF - see subclause 3.15.

So the "_(Required, deprecated in PDF 2.0)_" means that from up to and including PDF 1.7 the entry was required, but from PDF 2.0 the entry is no longer required and is officially deprecated (i.e. "should not be written and should not be read" - where "should" is a special ISO word meaning "recommended"). 

There are also various issues with **Length** in extant data, including its value being in _bytes_ (not bits, as it is defined); having a value that disagrees with other keys (e.g. algorithm), having some other value altogether, being required to be present but its value is effectively ignored (since things work with wrong values), etc. so what writers generate and what implementations appear to do is not an indication of what the spec is stating as valid for valid PDF. Please report all implementation issues to specific vendors.

**Comment by petervwyatt** [comment]
See also #184

**Comment by seehuhn** [comment]
Thank you, the formal definition of "deprecated" makes sense to me.  I am still not quite sure about the combination of "deprecated" and "required", though.  (Is there a formal definition of "required"?)  Is the logic here that when "deprecated" and "required" are both specified at the same time, then "deprecated" takes precedence?  Or is the logic that "deprecated in PDF 2.0" implicitly modifies the preceding clause into "required until PDF 1.7"?

To me as a reader, the document would have been clearer, if the text had been "required until PDF 1.7; deprecated in PDF 2.0" or similar.

**Comment by petervwyatt** [comment]
It's not an excuse, but it's how things have always been written in PDF specs (note that the version when introduced is also not always mentioned). (_self-promoting_: If you refer to the [Arlington PDF Model](https://github.com/pdf-association/arlington-pdf-model) then the definition of things is more formalized than the nuances of natural language.)

Further note that in this specific case the "required" vs "optional" in old specs was extra odd because it also had default values so even if it was not specified there was still a defined value - and hence why some creators never wrote it out, or readers might insist on the key but ignore the value. It was a unique mistake as far as we know...

**Comment by seehuhn** [comment]
Thanks for your explanations.  Since the spec is apparently how it's meant to be, and since I have now understood what "Required; deprecated in PDF 2.0" means in the spec, I'm closing this now.
