### ISSUE TITLE
Clarify that a stream length includes EOD

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#319]
Spun out from https://github.com/pdf-association/pdf-issues/issues/293

7.3.8.2 (Stream extent) says:

> Every stream dictionary shall have a Length entry that indicates how many bytes of the PDF file are used for the stream’s data. (If the stream has a filter, Length shall be the number of bytes of encoded data.) In addition, most filters are defined so that the data shall be self-limiting; that is, they use an encoding scheme in which an explicit end-of-data (EOD) marker delimits the extent of the data.

While every implementation that I know includes the bytes of the EOD marker in Length, it's not explicitly stated here. It would be easy to argue that the EOD marker is not "encoded data".

I'm sure there are clever ways to tweak the existing sentence on EOD, but KISS! I suggest adding another sentence to say "the Length value shall include the bytes of the EOD marker."

**Comment by MatthiasValvekens** [comment]
Not disagreeing in the least, but I've always read "encoded data" as "the output of the applicable encoding procedure(s) applied to the 'plain' data". Since the EOD marker (when applicable) is part of that output, it all works out.

I have no real objection to the proposed change, but IMHO we could also get away with an informative note along these lines, just in case people don't want to touch the normative words here:

> NOTE: The 'encoded data' of a stream encompasses the encoding's EOD marker, if the encoding scheme uses one.

**Comment by mkl-public** [comment]
If one makes this clear for EOD markers, one should also mention that any header data etc. also is included. Thus, I'd propose a more generic formulation, along the lines of
>NOTE: The 'encoded data' of a stream encompasses all enveloping markers of the encoding, e.g. end-of-data markers, if the encoding scheme uses them.

**Comment by petervwyatt** [comment]
PDF TWG agree to @mkl-public proposed note.
