### ISSUE TITLE
Unclear how multiple attribute objects with same owner apply to structure element

### ISSUE THREAD

**Issue by willkil** [pdf-association/pdf-issues#32]
Do all non-repeated attributes from multiple attribute objects with a repeated owner apply to a structure element?

14.7.6.1, Paragraph 1 defines:
-  **attribute object**: "a dictionary or stream that includes an O entry"
- **attributes**: "Other entries, except the NS entry, shall represent the attributes: the keys shall be attribute names, and values shall be the corresponding attribute values."

Paragraph 3 ("When an array...") states that when the owner is repeated and a given **attribute** (as opposed to **attribute object**) is also repeated, the later entry takes precedence. I interpret "entry" to mean a single attribute, not an array entry. This implies that the following two arrays of attribute objects on a TD structure element should be equivalent:
`[ << /O /Table /RowSpan 2 >> << /O /Table /ColSpan 2 >> ]`
`[ << /O /Table /RowSpan 2 /ColSpan 2 >> ]`

In contrast, I have seen two different PDF processors treat the first array as equivalent to specifying only one of the two attribute objects, although admittedly this happened on a PDF 1.5 document. I'm not sure what is the correct interpretation here.

Proposed Solutions (mutually exclusive). Replace the final sentence in paragraph 3 with:
1. "All the attributes in all such attribute objects apply to the structure element. If a given attribute is specified more than once, the attribute in the later (in array order) attribute object shall take precedence."
2. "The last such attribute object (in array order) shall take precedence."

**Comment by mrbhardy** [comment]
@willkil yes, the intent was to operate on the per attribute level and not at the object level.  In the example you provide, I would say that the end interpretation would be equivalent.

I'm trying to understand the ambiguity.  You point out that attribute is already correctly defined as the entry and we are indeed talking about repeated entries.  Given that key names must be unique in a given dictionary, it cannot be referring to order within an attribute object, because that's impossible (and undefined).  Therefore, I don't think this text needs changing.  This was actually added in PDF 2.0 because of the ambiguity in previous versions PDF 1.7 or earlier and inconsistent implementations.

**Comment by willkil** [comment]
@mrbhardy I thought someone could reasonably interpret "entry" in the final sentence to mean a separate attribute object dictionary within the array; an "array entry". After reading that you believe there is no ambiguity, I checked section 7.3.6 Array objects. I see that an object in an array is called an "element", not an "entry". Given that, I no longer believe it is reasonable to interpret "entry" in the final sentence to mean an attribute object dictionary. Thanks for helping clarify this.
