### ISSUE TITLE
Ambiguous/confusing wording in Algorithm 2.B (a) ISO32000-2:2020-with-errata

### ISSUE THREAD

**Issue by adenton0** [pdf-association/pdf-issues#325]
**Description**
In **"7.6.4.3.4  Algorithm 2.B: Computing a hash (revision 6 and later)", step (a):**

Clause (a) ends with "If checking the user password or creating the user key, K1 is the concatenation of the input password and K."

Now (in the opposite case, i.e. *not* "checking the user password or creating the user key) the previous text says that (summarizing/paraphrasing) K1 shall be 64 repetitions of (input password + K + the 48-byte user key).  *Clear enough*.

But it is *unclear* whether, in the "if checking the user password or creating the user key" case, K1 shall be:

- Either as (a) currently reads, "the concatenation of the input password and K",
- ** OR **
- (what I think is meant) _64 repetitions of_ (the concatenation of the input password and K).

Clause (a) right now literally implies K1 is just "one" repetition "if checking the user password or creating the user key" which I believe is incorrect and is upsetting/confusing to the reader.

**Proposed Remedy**
PROPOSAL:  Change the last sentence of (a) to read: "If checking the user password or creating the user key, K1 is 64 repetitions of the concatenation of the input password and K."
(If that is what is meant).

ANTIPROPOSAL:  If I am wrong, and it is actually _intended_ that "If checking the user password or creating the user key, K1 is the concatenation of the input password and K", then change the last sentence of (a) to read:  "If checking the user password or creating the user key, K1 is simply the concatenation of the input password and K, without any repetition."

**Additional context**
The publicly-available codebase "OpenPDF" ( https://github.com/LibrePDF/OpenPDF/ ) implements 64 repetitions for both cases (which I would expect from technical/crypto background).  Thus this favors my "PROPOSAL" intention and not that of the "ANTIPROPOSAL" above.

**Comment by MatthiasValvekens** [comment]
I concur that the number or repetitions should be 64 in both cases (also on the grounds that that is how it's done in all implementations that I'm aware of), and the current wording is indeed confusing: the first half of the paragraph appears to contradict the second half.

IMO "restatements" of this type are to be avoided in normative text because they're error-prone. Also, the whole "when checking the user key" condition is out of place, because whether the user key is to be considered or not is actually specified at all the "call sites" (for lack of a better word) of this algorithm elsewhere in the section. I'd rather address it holistically and clearly identify the parameters to the algorithm, than apply a spot fix locally. 🙂 

Here's a start. At the beginning of 7.6.4.3.4, insert the following:

> This algorithm takes the following parameters:
>  - a binary input string;
>  - the input password (NOTE: The sanitisation steps to apply to the password are specified in 7.6.4.3.3);
>  - optionally, a 48-byte user key; if unspecified, the user key shall be taken to be the empty string.

Then we can specify the calculation of K1 more succinctly as follows (replacing (a)):

> Make a new string, K1, consisting of 64 repetitions of the sequence: input password, K and the user key.

This more precise separation of the parameters requires some minor touch-ups elsewhere in the section; I'm happy to track those down if people are OK with this general direction.

**Comment by petervwyatt** [comment]
@MatthiasValvekens - assigning to you since you volunteered... thank you!

**Comment by MatthiasValvekens** [comment]
Proposed wording (sketch):

Replace (a) with something along the lines of:

> Make a new string K1:
>   - When checking the owner password / creating the owner key: K1 = 64* (password + K + user key)
>  - Otherwise: K1 = 64* (password + K)
