### ISSUE TITLE
`DecodeParms` cannot use an array that contains a dictionary?

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#359]
**Describe the bug**
I'm not sure whether is accidental or intentional. Sorry for the noise if it's intentional:

In table 5: There's this text:
`If there is only one filter and that filter has parameters, DecodeParms shall be set to the filter’s parameter dictionary unless all the filter’s parameters have their default values, in which case the DecodeParms entry may be omitted.`

It seems it says that if i have filters `F1` or `[F1]`,  neither `[D1]`, `[null]` nor `[]` is valid for this situation. I'm not sure if it's intentional or not.

Also Q:

In table 5: There's also this text:
`If there are multiple filters and any of the filters has parameters set to nondefault values, DecodeParms shall be an array with one entry for each filter in the same order as the Filter array: either the parameter dictionary for that filter, or the null object if that filter has no parameters.`

If i have filters `[F1 F2]` and params `[D1 null]`, can i write it as `[D1]` without the null or `D1` without the array in this case?

**Comment by MatthiasValvekens** [comment]
> If i have filters [F1 F2] and params [D1 null], can i write it as [D1] without the null or D1 without the array in this case?

Wouldn't this require the reader to somehow know that `D1` applies to `F1` and not `F2`? I don't think that's a safe assumption.

I read the rule as "as soon as even _one_ filter requires parameters, you need to ensure that the DecodeParms array is present and has as many (nullable) entries as there are filters". I think that's reasonable, because otherwise there's no universally unambiguous way of knowing which parameters apply to which filter AFAICT.

**Comment by petervwyatt** [comment]
> It seems it says that if i have filters F1 or [F1], neither [D1], [null] nor [] is valid for this situation. I'm not sure if it's intentional or not.
... or omitted altogether.

And, yes, fully intentional.
