### ISSUE TITLE
Output intents (14.11.5): combination constraints unclear

### ISSUE THREAD

**Issue by stechio** [pdf-association/pdf-issues#361]
`OutputIntents` entry (see document catalog dictionary (7.7.2) and page dictionary (7.7.3.3)) is defined as an array of output intent dictionaries which are distinguished by subtype (either predefined (`GTS_PDFX`, `GTS_PDFA1`, and `ISO_PDFE1`) or additional (see Annex E ("Extending PDF"))).

AFAIK, *the spec doesn't prescribe whether **multiple output intent dictionaries of the same subtype*** (eg, `GTS_PDFA1`) *can be added to an array*; real-world PDF files typically contain output intent dictionaries of *distinct* subtype (eg, `GTS_PDFA1` and `ISO_PDFE1`) only, so one might assume that adding multiple output intent dictionaries of the same subtype is pointless (but syntactically possible!). If this consideration is correct, the obvious question is: *why was `OutputIntents` entry defined as an array instead of a dictionary keyed by subtype?* (the latter would have been much more convenient (no output intent duplication for the same subtype, easy retrieval by subtype))

**Comment by petervwyatt** [comment]
I cannot speak to the original Adobe design goals, ideals, etc. for PDF 1.4 when **OutputIntents** were introduced. 

But I'd guess arrays were chosen as they provide a defined ordering. Indexing maps based on custom keys to arrays of objects (such as done in PDF 2.0 with extensions dictionary) only more recently became an acceptable design idiom. Core "general purpose" PDF provides flexible generic frameworks that others may bend (mandate, prohibit, restrict, etc.) to their specific needs. So if PDF doesn't say you cannot, then you can. Of course, what that means for "general purpose" PDF may well be implementation-dependent since it is unspecified in the core spec.

**OutputIntents** is already heavily entrenched in all existing subsets so changing anything potentially has very large ramifications. The subsets also already define requirements for handling duplicate subtypes.

**Comment by DietrichSeggern** [comment]
And in PDF/A-4 is specified that all OutputIntent entries need to use the same destination profile. In PDF/X-6 is specified that only one PDF/X OutputIntent entry may be present in the array.
