### ISSUE TITLE
Is the text matrix part of the "graphics state"?

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#368]
Section 8.4.2 states that the `q` operator pushes the entire graphics state on the stack, and `Q` then can restore the entire graphics state.  Does `Q` restore the text matrix?

More specifically, should the following content stream print "XXX" underneath "OOO" or should "XXX" and "OOO" overlap?

```
BT
/F 24 Tf
100 300 Td
q
(OOO) Tj
0 -30 TD
Q
(XXX) Tj
ET
```

(Full PDF attached: [test.pdf](https://github.com/pdf-association/pdf-issues/files/13502343/test.pdf) )

Some observations:
- Section 8.4.1 says that the graphics state holds the current "graphics control parameters".
- Table 51 says that there are "nine graphics state parameters" and section 9.3.1 says that "there are nine parameters in the text state".  The list of these 9 parameters (table 102) does not include the text matrix.
- The text after table 51 mentions the text matrix as one of "three additional text-related parameters".
- section 9.4.1 says that these "three parameters may be specified only within a text object and shall not persist from one text object to the next".
- If `q`/`Q` save the text matrix, is `BT ... q ... ET ... BT ... Q ... ET` allowed?
- Adobe Acrobat Reader and Google Chrome seem to restore the text matrix when `Q` is issued.
- Preview on Mac seems to get confused by the attached PDF file, misplacing the "OOO".

**Comment by mkl-public** [comment]
The background of this issue is that up to ISO 32000-2:2017 **q** and **Q** were categorized as _special graphics state operators_. Thus, you were not allowed to use them in text objects. As the text matrices are reset at the start of a text object, storing them in the graphics states on the stack was futile.
In ISO 32000-2:2020 **q** and **Q** were re-categorized as _general graphics state operators_ and, therefore, are now allowed in text objects.
It appears like one objective of this change was to allow saving and restoring the text matrices but this indeed is not communicated clearly in the spec.

Concerning your nesting question:
> If `q`/`Q` save the text matrix, is `BT ... q ... ET ... BT ... Q ... ET` allowed?

Section 9.4.1 requires proper (separate) nesting. While the example under that does not exactly reflect your example, it seems pretty clear that your example is not allowed.

Furthermore,
>Preview on Mac seems to get confused by the attached PDF file, misplacing the "OOO".

Preview on Mac in general is not exactly known for following the PDF spec. In this case, though, it most likely simply has not implemented the above-mentioned change in ISO 32000-2:2020 but tries the best it can to render the PDF with the old rules.

**Comment by seehuhn** [comment]
Ah, thanks.  I had missed the text about nesting in section 9.4.1.  I agree, this makes it clear that my example is not allowed.

So I guess the solution would be to either make it clear that the text matrices are part of the graphics state, or alternatively to say that `q` saves the graphics state plus the text matrices?

**Comment by mkl-public** [comment]
>So I guess the solution would be to either make it clear that the text matrices are part of the graphics state, or alternatively to say that `q` saves the graphics state plus the text matrices?

I think so, too. I would prefer the former but that would require searching for all mentions of the graphics state and the text matrices and checking whether they require some updating.

**Comment by petervwyatt** [comment]
Deciding to cache / pre-compute the text matrix as part of the overall graphics state is an implementation design choice, since everything needed is already determinable from data already formally defined to be in the graphics state (text state parameters, special graphics state), and the operands of the text-positioning operators:

> The values of the text state parameters shall be consulted when text is positioned and shown (using the operators described in 9.4.2, "Text-positioning operators" and 9.4.3, "Text-showing operators"). In particular, the spacing and scaling parameters shall be used in a computation described in 9.4.4, "Text space details".

**Comment by petervwyatt** [comment]
> It appears like one objective of this change was to allow saving and restoring the text matrices but this indeed is not communicated clearly in the spec.

Technically not the text matrices (since that's transitory), but the text state parameters, general graphics state and color operators as shown by Figure 9 (which is normative).

**Comment by seehuhn** [comment]
Sorry, I missed this post earlier.

> Deciding to cache / pre-compute the text matrix as part of the overall graphics state is an implementation design choice, since everything needed is already determinable from data already formally defined to be in the graphics state (text state parameters, special graphics state), and the operands of the text-positioning operators:
> 
> > The values of the text state parameters shall be consulted when text is positioned and shown (using the operators described in 9.4.2, "Text-positioning operators" and 9.4.3, "Text-showing operators"). In particular, the spacing and scaling parameters shall be used in a computation described in 9.4.4, "Text space details".

What I am asking about is the parameter $T_m$.  This is not listed in table 102, and cannot be computed from the values in table 102.  Is $T_m$ "formally defined to be in the graphics state"?  If so, where does this happen?

**Comment by petervwyatt** [comment]
9.4.1:
> In addition, three parameters may be specified only within a text object and shall not persist from one text object to the next:
> • $T_m$, the text matrix.
> • $T_{lm}$, the text line matrix.
> • $T_{rm}$, the text rendering matrix, which is actually just an intermediate result that combines the effects of text state parameters, the text matrix (Tm), and the current transformation matrix.

...

Table 105, **BT**:
> Begin a text object, initializing the text matrix, $T_m$, and the text line matrix, $T_{lm}$, to the identity matrix.

Remember also Figure 12 in 8.3.2.5 - unlike $T_{rm}$, $T_m$ and $T_{lm}$ don't represent "absolute" matrices mapping all the way into device space. 

However, I agree that with the clarified behaviour of having `q`/`Q` inside text objects added in PDF 2.0, wording now neglects to mention that these text matrices _additionally_ need to get pushed/popped within each single text object. But they're not defined outside of text objects so they're not part of what is otherwise called the "graphics state" - accidentally implying that could lead to even more confusion with other statements elsewhere in the spec.

Since `q`/`Q` are defined back 8.4.2, well before text is introduced in clause 9, this is going to have to be fixed by forward/back referencing (at least as far as band-aid patches appropriate for errata - we're not doing large scale surgery of altering terminology, rewriting, moving around slabs of text, etc. for errata. Longer term that would be better.).

**Comment by petervwyatt** [comment]
Trying to converge on an appropriate errata-level solution: 

* at the very end of clause 9.4.1 (after the NOTE) add new text:
    > Within a text object, the graphics state stack operators **q** and **Q** (see 8.4.2, "Graphics state stack") shall additionally push and pop $T_m$ and $T_{lm}$ as part of the graphics state stack.

* in 8.4.2, append a new sentence to the end of the last para:
    > See 9.4.1, "General" for additional information that must be managed as part of the graphics state stack when **q** and **Q** operators occur in text objects.

**Comment by petervwyatt** [comment]
PDF TWG agree - also ask for test PDF to be added here.

**Comment by petervwyatt** [comment]
Hand-crafted simplistic test case: [TextObject-PushPopTextMatrix.pdf](https://github.com/pdf-association/pdf-issues/files/14327412/TextObject-PushPopTextMatrix.pdf)

**Comment by mkl-public** [comment]
> Hand-crafted simplistic test case: [TextObject-PushPopTextMatrix.pdf](https://github.com/pdf-association/pdf-issues/files/14327412/TextObject-PushPopTextMatrix.pdf)

IMO the file behaves reasonably in Acrobat.

But I don't understand the `so "20 TL" above is lost` in the `this resets $T_m$, $T_lm$ so "20 TL" above is lost` comment in
```
  q
      1.2 0 0 1.2 100 300 Tm    % set $T_m$
      20 TL                     % reduce line spacing $T_lm$
      1 0 0 rg % red
      (Line 1 in push #1) '
      0 0 1 rg % blue
      (Line 2 in push #1) '
  Q
  
  (Line 3 in middle of text object, outside q/Q) '
% ET % TRY UNCOMMENTING THIS LINE as this resets $T_m$, $T_lm$ so "20 TL" above is lost
  0 1 0 rg % green
% BT  % TRY UNCOMMENTING THIS LINE
```
If the PDF viewer supports **q** and **Q** inside text objects as per change between ISO 32000-2:2017 and ISO 32000-2:2020, _"20 TL" above_ has already been _lost_ with the **Q** 3 lines before the **ET**; and if it doesn't and simply ignores the then forbidden **q** and **Q**, the _"20 TL" above_ has been stored in $T_L$ and, therefore, is not _lost_ here at all, in particular not by ending the current text object **ET** and starting a new one **BT**,

**Comment by petervwyatt** [comment]
Sorry - those comments were from a previous iteration. Just ignore them...
My informal testing shows reasonable conformance and consistency by the vast majority of viewer (I assume because of competitor testing).
