### ISSUE TITLE
possible mistake in given range of the flatness tolerance

### ISSUE THREAD

**Issue by seehuhn** [pdf-association/pdf-issues#371]
Table 50 and section 10.7.2 describe the flatness tolerance as positive number.  In contrast, table 56 states that the argument of the `i` operator (for setting the flatness tolerance) is a number in the range 0 to 100 (and also states that "a value of 0 shall specify the output device’s default flatness tolerance").  Table 57 describes the value of the `FL` entry in a graphics state parameter dictionary (another way of setting the flatness tolerance) simply as a "number".

These descriptions allow for the possibility that the flatness tolerance might be set to values larger than 100 using a graphics state parameter dictionary.  It is also unclear whether setting flatness to 0 via a graphics state parameter dictionary will be interpreted as the device’s default flatness tolerance.  It would be nice to clarify whether or not the two ways of setting the flatness tolerance are different in these regards.

Suggested solution: Move or copy the text "flatness is a number in the range 0 to 100; a value of 0 shall specify
the output device’s default flatness tolerance" from table 56 to section 10.7.2, applying these explanations to the parameter itself rather than to the argument of the `i` operator.

**Comment by petervwyatt** [comment]
See also errata #15 and #191

**Comment by petervwyatt** [comment]
@seehuhn - I think you mean "Table 52 — Device-dependent graphics state parameters" rather than Table 50. Otherwise references are correct. And the intention is that both the **i** operator and **FL** entry are the same.

We generally prefer not to duplicate requirement text as it becomes a maintenance issue (and this is possibly the root cause of this issue!) so I suggest instead:

* Table 52, "flatness": delete parenthetical "_(positive number)_" so description doesn't provide any numeric requirements. Leave the initial value here (as 1). Rely on 10.7.2. having all requirements.
* Table 56, **i** operator: delete 2nd sentence and rely on 10.7.2. having all requirements.
* Table 57, **FL** entry: no change needed - already references to 10.7.2.
* 10.7.2 "Flatness Tolerance", 1st para: replace last sentence "_It shall be a positive number._" with "_It shall be a number in the range 0 to 100, where a value of 0 shall specify the output device’s default flatness tolerance. The value indicates the maximum error tolerance measured in output device pixels._"

**Comment by petervwyatt** [comment]
PDF 1.0 has 0-100. 
PDF TWG agree.

**Comment by lrosenthol** [comment]
It's not a percentage, but 0-100 is correct.  Agree with proposal above to resolve.

**Comment by petervwyatt** [comment]
PDF TWG agree
