### ISSUE TITLE
Lack of clarity on requirement of existence of `V` key on Text fields

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#387]
12.7.5.3 (paragraphs after table 231) does not clearly specify whether the `V` key is required for text fields - I don't see why it would need to be - and what behavior is when not present.

**Comment by petervwyatt** [comment]
I combine this statement from the para below Table 231: "_The field’s text shall be held in a text string (or, beginning with PDF 1.5, a stream) in the **V** (value) entry of the field dictionary._" with "Table 226 — Entries common to all field dictionaries" and "Table 228 — Additional entries common to all fields containing variable text" to conclude that **V** is optional, but if its value needs to be defined then V "shall" be present as a text-string or stream (only).

I agree that this could be clearer as **DV** is also not mentioned at all.

I also see an error that was introduced in ISO 32000-2:2017 - the last bullet starting "_XML format..._" is supposed to be just one sentence. Instead, the general normative text describing **MaxLen** has been merged with that bullet, rather than standing alone - since **MaxLen** applies to all text fields, not just XML file selection. See ISO 32000-1:2008 and earlier Adobe specs.

**Comment by petervwyatt** [comment]
@lrosenthol - could you please propose improved wording/clarifications for this and related errata?

**Comment by JohnBrinkman** [comment]
duplicate of https://github.com/pdf-association/pdf-issues/issues/392

**Comment by petervwyatt** [comment]
Thanks for spotting. Closing this errata as a duplicate.
