### ISSUE TITLE
"PDF Declarations" specification lacks some clarity and is inconsistent in the use of trailing `/` and `#`

### ISSUE THREAD

**Issue by petervwyatt** [pdf-association/pdf-issues#395]
The "PDF Declarations" specification lacks some clarity and is inconsistent in the use of trailing `/` and `#`:

* a correction was recently done for WTPDF declarations, changing from `http://pdfa.org/declarations#wtpdf-reuse1.0` to `http://pdfa.org/declarations/wtpdf#reuse1.0` - or should that be `http://pdfa.org/declarations/wtpdf/#reuse1.0`?
    -  This issue is also to form a matter of record that this specific correction happened in the first place 

* the [example here](https://pdfa.org/declarations/#HIPAA) has URI `.../declarations#hippa` but the PDF Declarations example on page 6 uses the URI `.../declarations/#hipaa` - these should be the same for consistency, but which one is "more correct"?
    - based on wording in XMP (see below) I'm guessing the more correct usage is always to include the `/` before the `#`, since the official PDF declarations namespace URI ends with a `/` and is thus this URI is then a simple concatenation.

* is there (or do we desire "should" or mandate "shall"?) a single correct way to specify URIs for declarations in the use of paths (`/`) or fragments (after `#`)? Should there always be a `/` before any `#`? Are there any recommendations for constructing well-designed PDF Declaration URIs (e.g. why was the original wtpdf declarations unsuitable? Why aren't WCAG 2.2 declarations also not done using a path?)
    -  ISO 16684-1:2019 (XMP) clause 6.2. states: "_Two XMP names shall be equivalent if their namespace URIs are identical and their local names are identical. This comparison shall be physical, byte-for-byte equality using the same Unicode encoding. Other processing, including but not limited to Unicode character normalizations, shall not be applied._" and "_A namespace URI used in XMP should end in a character that is not allowed in an XML NCName (the local name). Recommended characters are the slash ("/", U+002F) or the number sign ("#", U+0023). This can improve compatibility with applications that concatenate the namespace URI and local name, avoiding potential collisions._" and further discussed in "B.3 Namespace URI termination"
    - it should **not** be assumed that every situation can call some URI normalization API e.g. the Acrobat custom XMP panels (https://pdfa.org/discovering-pdf-metadata/) are purely declarative so there needs to be consistency so precise string matching can be done

**Comment by petervwyatt** [comment]
@bdoubrov - I think you found the issue in the first place
@faceless2 @u-fischer - I think you both have support for this coded
@DietrichSeggern - as our resident XMP expert/PL
@mrbhardy - as original designer of PDF Declarations

Intention is to discuss this in the next PDF TWG (if needed), only because this is sooner than the next Reuse TWG. But please add any thoughts or comment in this issue.

**Comment by petervwyatt** [comment]
@faceless2 we need to change _something_ since the web page and the spec disagree on HIPPA. Do you have a preference?

**Comment by u-fischer** [comment]
Well the main namespace identifier (`xmlns:pdfd="http://pdfa.org/declarations/"` ends with a slash and so is fine for XMP. 

As @faceless2  I think that declaration URIs are opaque strings and even if they not end with hash or slash it should be ok. So the main question is how to build in the names in a consistent way. In view that all declaration URIs have no slash before the hash  (e.g. `http://pdfa.org/declarations#wcag22a`) I wonder a bit why this was now added to wtpdf. Both the old URI (`http://pdfa.org/declarations#wtpdf-reuse1.0`) and  your suggestion `http://pdfa.org/declarations/wtpdf#reuse1.0`  (if one wants some subpath) looks more consistent to me than the current `http://pdfa.org/declarations/wtpdf/#reuse1.0`.

**Comment by faceless2** [comment]
> we need to change something since the web page and the spec disagree on HIPPA. Do you have a preference? 

Ah, I understand. After an email from @DuffJohnson a few hours ago re. this mismatch, I thought that decision had already been made and the change was to `http://pdfa.org/declarations/wtpdf#reuse1.0` - which is what @mrbhardy  suggests anyway.

They obviously need to align :smile:, so that works for me too.

**Comment by davidcarlisle** [comment]
> I suggest we correct WTPDF to: http://pdfa.org./declarations/wtpdf#reuse1.0

presumably also change

http://pdfa.org/declarations/wtpdf/#reuse1.0-validated

http://pdfa.org/declarations/wtpdf/#accessibility1.0

http://pdfa.org/declarations/wtpdf/#accessibility1.0-validated


---

Not directly related but have you considered adding some text with those anchors to the page

If someone looking in a pdf finds http://pdfa.org/declarations/wtpdf#accessibility1.0-validated and wonders what it stands for, the natural thing is to follow that link rather than read a spec, and currently all four of them just resolve to the same place at the top of the page https://pdfa.org/wtpdf, which isn't so  informative about the different URL.  The natural text for those anchors  is on the page https://pdfa.org/declarations/ but that isn't where you land if you just follow the declaration URL 

Currently http://pdfa.org/declarations/wtpdf redirects to http://pdfa.org/wtpdf if it redirected to http://pdfa.org/declarations/  (or had its own page at that URL) then the anchors could be handled far more naturally.

the wtpdf ones land on the wrong page, the pdf/ua ones land on the right page but the anchors don't match eg the declaration 

http://pdfa.org/declarations#pdfua1-validated

redirects to https

https://pdfa.org/declarations#pdfua1-validated

but the page anchor is

https://pdfa.org/declarations#PDF_validated_as_conforming_to_PDFUA-1

It would be helpful if the anchor in the page was  `pdfua1-validated`

**Comment by petervwyatt** [comment]
Thanks all - the conclusion is clear. Changes that I can see that need doing are:

* in "PDF Declarations" spec, correct section 7.2 PDF Declaration example from `<pdfd:conformsTo>http://pdfa.org/declarations/#hipaa</pdfd:conformsTo>` to `<pdfd:conformsTo>http://pdfa.org/declarations#hipaa</pdfd:conformsTo>` so it matches https://pdfa.org/declarations/
    - I would also suggest adding an informative note to Table 2, **pdfd:conformsTo** along the lines of "The convention used by PDF Declarations is to use `#` as the only separator between the URI path and fragment components as shown in the example in 7.2."

* in WTPDF spec, correct two occurrences of `.../wtpdf/#...` to `.../wtpdf#...` in each of section 6.1.2 and 6.1.3

* update https://pdfa.org/declarations/ page for the 4 WTPDF declarations so they are not `.../wtpdf/#...`, but `.../wtpdf#...`. 
    - Also add a small pointer back to this errata at the bottom of the page in case anyone wonders what changed or why
    - add matching URI anchors for the listed declarations to https://pdfa.org/declarations/ (even tho' URIs don't have to technically resolve I can see how this would be helpful. Current anchors shouldn't be replaced in case people have them bookmarked.)

**Comment by davidcarlisle** [comment]
> even tho' URIs don't have to technically resolve I can see how this would be helpful. 

Yes this is similar to XML namespace URL which are really just opaque strings but good practice is to have an explanatory page at the URL.


The W3C for example make that a requirement for all namespace URL under www.w3.org.

MathML is:

http://www.w3.org/1998/Math/MathML

**Comment by petervwyatt** [comment]
WTPDF and PDF Declarations documents will be reviewed in the upcoming PDF/UA TWG meeting in Tokyo.

**Comment by petervwyatt** [comment]
WTPDF and Declarations errata integrated with [this commit](https://github.com/pdf-association/pdf-issues/commit/ec789c87cc6446b3d4a9e31dff049c9520863cc8)
