### ISSUE TITLE
Several occurrences of `/BDC` instead of `BDC`

### ISSUE THREAD

**Issue by pgundlach** [pdf-association/pdf-issues#415]
Annex H

Example after Figure H.9, example in H.8.4 Example of Sub standard structure type, and example after Figure H.7 

use `/BDC`, but I assume that `BDC` is meant. 

For example (after Figure H.9):

```
/P <</MCID 1>> BDC
BT T* (INDEX) Tj ET EMC
/Lbl <</MCID 11>> BDC
BT T* (1. ) Tj ET EMC
/LBody <</MCID 12>> /BDC
BT (Cats ) Tj ET EMC
/Lbl <</MCID 21>> BDC
```

**Comment by petervwyatt** [comment]
There looks to be 15 or so instances of `/BDC` (name) rather than **BDC** (operator) all in Annex H (informative) Example PDF files. But thankfully no `/EMC'.

Since this is just an informative annex, the simplest solution is to post the solution as an EDITOR NOTE at the start of Annex H rather than have to markup all occurrences.

**Comment by petervwyatt** [comment]
PDF TWG agree
