### ISSUE TITLE
is the value declaration in the XMP Schema for declaration correct?

### ISSUE THREAD

**Issue by u-fischer** [pdf-association/pdf-issues#458]
["PDF Declarations A use of ISO 32000"](https://pdfa.org/wp-content/uploads/2023/12/PDF-Declarations.pdf) contains as attachment an `.xmp` file which shows the needed PDF/A extension schema. 

In this `.xmp` file two types are declared as resources

~~~~
<pdfaType:type>claim</pdfaType:type>
....
<pdfaType:type>declaration</pdfaType:type>
~~~~

These types are then used like this in a `valueType`:

~~~~
<pdfaField:valueType>Bag claim</pdfaField:valueType>
<pdfaProperty:valueType>Bag declaration</pdfaProperty:valueType>
~~~~

I took that as a syntax for "Bag of claims"/"Bag of declarations", but as been reported in our github https://github.com/latex3/tagging-project/issues/375#issuecomment-2260297958, the xmp validator at https://www.pdflib.com/pdf-knowledge-base/xmp/free-xmp-validator/ complains about undeclared custom value types:

~~~~
XMP data is invalid

Reason: XMP metadata: Description of custom value type 'Bag claim' missing in PDF/A Field Value Type
~~~~

Could you clarify if the example schema for declarations is correct (and if not provide a corrected schema as an example)?

**Comment by ozross** [comment]
Has anyone at Adobe, or elsewhere, been looking at this?
It would be nice to have it clarified (fixed, even better) before the Prague meetings.

**Comment by DietrichSeggern** [comment]
I think that PDF Lib's XMP validator is wrong in this case. The value types "claim" and "declaration" are defined in the Extension Schema.
The example PDF embedded into the Declarations Specification is validated e.g. in Acrobat Preflight.

**Comment by u-fischer** [comment]
@DietrichSeggern do you know a source for the `Bag claim` syntax? I couldn't find anything about it in the normal XMP documentations.

**Comment by DietrichSeggern** [comment]
For the properties that is defined in ISO 16684-1 in 7.7. There is e.g. this example:
"<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:dc="http://purl.org/dc/elements/1.1/">
<rdf:Description rdf:about="">
<dc:subject>
<rdf:Bag>
<rdf:li>XMP</rdf:li>
<rdf:li>metadata</rdf:li>
<rdf:li>ISO standard</rdf:li>
</rdf:Bag>
</dc:subject>
</rdf:Description>
</rdf:RDF>"

For the extension schema that is only specified in the PDF/A standards since they are only required there.

**Comment by petervwyatt** [comment]
So I think this issue can now be closed?
Looks like a bad implementation...

**Comment by ozross** [comment]
Hi Dietrich.

Yes, exactly.

The XMP documentation specifically states that being valid as RDF does *not* imply being valid as XMP.
The PDFlib RDF validator is happy with ‘Bag declaration’ but not their XMP validator.

Personally I’m happy either way, but need to know what to freeze into a LaTeX package’s code before making it publicly available.

I think we need at least a statement from PDFlib about this, and whether there will be any change, so that documents can be produced satisfying all available validation tools, when used correctly.

Cheers
   Ross



Sent from my iPhone

On 30 Sep 2024, at 11:59 PM, Dietrich vonSeggern ***@***.***> wrote:

﻿

For the properties that is defined in ISO 16684-1 in 7.7. There is e.g. this example:
"<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#<http://www.w3.org/1999/02/22-rdf-syntax-ns#>"
xmlns:dc="http://purl.org/dc/elements/1.1/"><http://purl.org/dc/elements/1.1/%22%3E>
<rdf:Description rdf:about="">
dc:subject
rdf:Bag
rdf:liXMP</rdf:li>
rdf:limetadata</rdf:li>
rdf:liISO standard</rdf:li>
</rdf:Bag>
</dc:subject>
</rdf:Description>
</rdf:RDF>"

For the extension schema that is only specified in the PDF/A standards since they are only required there.

**Comment by DietrichSeggern** [comment]
PDFlib had been acquired by apryse, you will have to try there...
