### ISSUE TITLE
Typos in Table 404 for Trap network annotations

### ISSUE THREAD

**Issue by t-merz** [pdf-association/pdf-issues#46]
Trap network annotations are deprecated and the error goes back the PDF 1.3 Reference, but the following should probably be corrected nevertheless. Table 404 "Additional entries specific to a trap network appearance stream" contains the following obvious typos:

"Valid values are DeviceGray, DeviceRGB, DeviceCMYK, DeviceCMY, DeviceRGBK, and DeviceN."

This should probably read:

"Valid values are DeviceGray, DeviceRGB, DeviceCMYK, and DeviceN."

**Comment by petervwyatt** [comment]
A search through ISO 32000-2 shows this is the only occurrence of "DeviceCMY" (with no "K").
Proposed solution as above.

**Comment by MPBailey** [comment]
The text explicitly identifies the value as being "The name of the process colour model that was assumed when this
trap network was created"; in other words, it's not tied to any PDF colour space.
I've worked with devices using DeviceCMY and DeviceRGBK process colour models, albeit not for some years now.
Given that this entire section is deprecated I would leave it as is.

**Comment by petervwyatt** [comment]
@MPBailey Thank you for that valuable input! I think you are indeed correct - this supports the less common and unusual process models using what might otherwise be thought of as only PDF color spaces. Will leave as-is (not the least because this is very old wording and deprecated).

Replacing "proposed solution" with "won't fix"
