### ISSUE TITLE
Timestamp signatures currently allowed before Certifying signatures

### ISSUE THREAD

**Issue by lrosenthol** [pdf-association/pdf-issues#55]
12.8.1, fourth bullet, about timestamp signatures

Add "These shall follow the certification signature if one is present." as the second sentence, to match the same language for approval signatures.

**Comment by petervwyatt** [comment]
@lrosenthol The title of this is truncated/abbreviated - could you please fix?

And I think you are referring to the 2nd set of bullets in clause 12.8.1, where the 4th bullet in question is immediately below NOTE 2 - is that correct?

**Comment by lrosenthol** [comment]
Title fixed, and yes to the location...

**Comment by MatthiasValvekens** [comment]
I upvoted the proposed solution, but I'd like to raise one potential objection that occurred to me this morning: in some situations where certification signatures may be used, the signer/certifier might want to prove that their signature was created _after_ some given date.  An easy way to do that (in a PDF-compatible way) would be to first add a document timestamp to the file, and then add the certification signature.

The order is important here, because the certification signature would necessarily have to cover the timestamp as well in this scenario.

Alternatively, the signer could add a signed attribute with a timestamp token in it (i.e. CAdES's `content-time-stamp` attribute), but I'm not sure to what degree the use of this attribute is supported in PDF processors today. That being said, it's explicitly called out as allowed in PAdES (ETSI EN 319 142-1, clause 5.2), for what it's worth.

If we decide that the above is a viable alternative, then I'm OK with the proposed solution.


Just putting that out there before we discuss it at the PDF TWG.

**Comment by petervwyatt** [comment]
PDF TWG approved
