### ISSUE TITLE
Revisit strategy about E4X support. 

### ISSUE THREAD

**Issue by crlf0710** [pdf-association/pdf-issues#70]
E4X (ISO/IEC 22537:2006) is a technology that adds a few XML-related extensions to ECMAScript language. Currently E4X is largely deprecated technology, and implies a major implementation burden to PDF developers, since none of the current version of most popular ECMAScript engines support E4X technology.

Currently E4X is a normative reference of ISO 21757-1:2020, whose draft is a normative reference of ISO 32000-2. Personally i think it would be nice to just deprecate all futures uses of E4X in a future edition of ISO 21757, and does a reference update to ISO 32000.

If this is impossible, (for backward compatibility reasons, for example), at the minimum i think it would nice to add it as an entry to "12.11.2 Requirement types", so pdf applications can emit nice diagnostics about what and why...

**Comment by petervwyatt** [comment]
Technically this is not a bug, but an enhancement. Looking for input from others...

**Comment by petervwyatt** [comment]
This issue was discussed during the virtual meeting of ISO TC 171 SC 2 WG 9 last night.

To summarize for others:
* earlier versions of PDF actively used E4X for use-cases such as using embedded XML inside PDFs as a data source for AcroForms (XML data would be a PDF attachment); prior to AcroForm submission, pre-processing submitted data as XML (when not using XFDF); and processing XMP and XFA via E4X.
* existing files with a dependency on E4X from earlier versions of PDF still exist so PDF 1.x processors still need to support E4X
* popular open-source JavaScript engines have removed E4X support in line with modern JavaScript changes
* WG9 agreed that PDF 2.0 should **not** depend on E4X as the JavaScript landscape has significantly changed
* WG9 also acknowledged that such a decision means that "upgrading" PDF 1.x files that rely on E4X to PDF 2.0 is no longer trivial/possible. This creates a forward-compatibility issue that is acknowledged and accepted.

The agreed solution is for WG9 to update [ISO 21757-1:2020 "Document management — ECMAScript for PDF — Part 1: Use of ISO 32000-2 (PDF 2.0)"](https://www.iso.org/standard/71559.html) at some time in the future. No changes are needed to ISO 32000-2:2020 (PDF 2.0) as it does not mention or refer directly to E4X - it 'inherits' the reference via an undated normative reference to ISO 21757-1. Until such time, this proposed resolution will be recorded here and at [https://www.pdfa.org/pdf-issues/](https://www.pdfa.org/pdf-issues/) once the PDFa PDF TWG agree.

Note also that ISO 32000-1:2008 (PDF 1.7) is unaffected as it does not reference ISO 21757-1 - and the title of ISO 21757-1 clearly indicates it is for PDF 2.0 only anyway. So ISO 32000-1:2008 (PDF 1.7) will continue to depend on E4X.

@lrosenthol and @philspreier - did I miss anything?

**Comment by petervwyatt** [comment]
PDF TWG agree

**Comment by petervwyatt** [comment]
PDF TWG agree to publish under top level specs
