### ISSUE TITLE
Disconnect between interactive form dictionaries and resource dictionary documentation

### ISSUE THREAD

**Issue by MPBailey** [pdf-association/pdf-issues#92]
The DR entry in Table 224 (Entries in the interactive form dictionary) describes the value as "A resource dictionary (see 7.8.3, "Resource dictionaries") containing default resources (such as fonts, patterns, or colour spaces) that shall be used by form field
appearance streams."

7.8.3 (Resource dictionaries) includes a series of 4 bullets that appear to be intended to be an inclusive list of all places that resource dictionaries should be used. None of those bullets explicitly refer to annotations and the 3rd bullet seems to rule out any use of a default resource dictionary.

Presumably one of those places is missing something to explain the disconnect, but what?

It seems possible that DR is intended for use only for variable text, but that is not stated (it is for DA and Q)?

**Comment by petervwyatt** [comment]
@lrosenthol - are you able to shed light on this please?

**Comment by lrosenthol** [comment]
The bulleted list in 7.8.3 needs to be expanded to include `DR` in the specific context of AcroForm fields.

To answer @MPBailey - `DR` applies to any/all AcroForm fields (text, buttons, etc.)

**Comment by petervwyatt** [comment]
PDF TWG agree. I will wordsmith.

**Comment by petervwyatt** [comment]
On deeper investigation after the PDF TWG meeting on 9 July where it was stated that **DR** can get used via inheritance to locate annot resources after looking in the appearance stream **Resources** - and also correcting @MPBailey original comment, the 3rd bullet does mention annots:

> * For other content streams, a PDF writer shall include a **Resources** entry in the stream's dictionary specifying the resource dictionary which contains all the resources used by that content stream. This shall apply to content streams that define form XObjects, patterns, and annotation appearances.

Note the word "all" in the first sentence! So this currently states that all annot appearance streams shall have a **Resources** entry and it shall always contain all needed resources... so therefore there is no need for inheritance to **DR**! 

I also found the following statements in 12.7.4.3 by searching for "DR" (case sensitive):

1. first bullet below Table 228:

> For non-rich text fields, the appearance stream — which, like all appearance streams, is a form XObject — has the contents of its form dictionary initialised as follows:
• The resource dictionary (**Resources**) shall be created using resources from the interactive form dictionary’s **DR** entry (see "Table 224 — Entries in the interactive form dictionary").

so in this case the **DR** entry is effectively a duplication of **Resources** (which is always present as AP is always present) and therefore no inheritance is required.

2.  A few paras lower down:
> To update an existing appearance stream to reflect a new field value, the interactive PDF processor shall first copy any needed resources from the document’s **DR** dictionary (see "Table 224 — Entries in the interactive form dictionary") into the stream’s **Resources** dictionary. (If the **DR** and **Resources** dictionaries contain resources with the same name, the one already in the **Resources** dictionary shall be left intact, not replaced with the corresponding value from the **DR** dictionary.) ...

Admittedly this statement is under subclause "12.7.4.3 Variable text" so logically only applies to variable text fields, whereas **DR** is defined more broadly in Table 224 under clause 12.7.3 "Interactive form dictionary" and thus applies to buttons, choice fields, signature fields as well as variable text. But I am not sure if **DR** resources makes any sense for those fields...

So I am inclined to think that the current wording in clause 7.8.3 regarding Resources for annoys is correct (at least for variable text fields) and does **not** need changing to account for DR.

Since this goes against what the PDF TWG decided, I will leave this issue open for discussion next time around.
Appreciate any comments from @MPBailey and @lrosenthol before then!

**Comment by lrosenthol** [comment]
I have verified that Adobe's implementation **does** treat the DR as a "fallback" case when it cannot locate resources (esp. fonts!) in a Widget's /AP's resource dictionary.

However, it most certainly considers this a "worst case scenario" - so if we decide to leave that behavior as "implementation dependent" or "out of scope", then I have no objection.

**Comment by MPBailey** [comment]
Peter's analysis suggests that a file that includes annotations with DR but not Resources is invalid, and therefore how an application responds to that situation is out of scope.

It also suggests that the only documented use for DR in a valid PDF file is in updating appearance streams if the field value of an annotation is amended, and we have previously agreed that that is implementation-dependent.

That implies that the DR row of table 224 should be amended to say that it's there in support of updating appearance streams. There would be additional changes required if we go down that route, such as in the para following the example in 12.7.4.3.

**Comment by petervwyatt** [comment]
@MPBailey - I'm not sure I agree with your logic. 7.8.3 states **Resources** "... contains all the resources _used_ by that content stream." while below Table 228 states "... shall first copy any _needed_ resources from the document’s **DR** dictionary". Italic emphasis is mine.

So for a valid PDF (and not considering the fallback case @lrosenthol discusses), a **Resources** dict always needs to be pure a subset of **DR** (including the degenerate 'no-resources-are-needed' and the 'every-DR-resource-is-needed' cases).  This also means **Resources** cannot have additional resources that are not in **DR**.

**Comment by MPBailey** [comment]
Apologies, to re-state my 1st para from above: "Peter's analysis suggests that a file that includes annotations with DR but whose appearance stream(s) require resources that are not present in their Resources dictionary is invalid, and therefore how an application responds to that situation is out of scope."

That doesn't change my conclusion at all.

**Comment by petervwyatt** [comment]
@MPBailey - sorry we didn't get to discuss this at today's PDF TWG.

I assume what you are referring to as your conclusion is the need to clarify/fix this sentence (para below example in 12.7.4.3):
> The specified font value shall match a resource name in the **Font** entry of the default resource dictionary (referenced from the **DR** entry of the interactive form dictionary; see "Table 224 — Entries in the interactive form dictionary").

Maybe something like:
> The specified font value shall match a resource name in the **Font** entry of the default resource dictionary. This font can be an indirect reference to the required font resource in the **DR** entry of the interactive form dictionary; see "Table 224 — Entries in the interactive form dictionary").

So do you also think we should add the logical corollaries somewhere?:
* the **Resources** dictionary of an appearance stream for an interactive form needs to be a subset of the **DR** resources; and
* the **Resources** dictionary of an appearance stream for an interactive form cannot have additional resources that are not in **DR**.

**Comment by petervwyatt** [comment]
PDF TWG: 12.7.4.3 is discussing **DA** which only uses **DR** (**DA** is not an appearance stream used for rendering). Appearance stream generation is currently undefined in ISO 32000-2:2020 (too hard!)
No fix.
