### ISSUE TITLE
No way described to force a new physical page?

### ISSUE THREAD

**Issue by hvbtup** [pdf-association/pdf-issues#97]
**Describe the bug**

Still - even in 2021 - actually printing a PDF document is a common use case.
It seems that there is no way to specify inside a PDF document that a certain logical page should start on a new physical page even while printing Duplex.

**Additional context**

A common use case for PDF is to send a PDF file to someone who should be able to print the document the right way - the receiver should be able to decide if  the doc is printed in duplex or simplex mode.

However, some documents are meant to be "dividable" when printed. E.g. a work-list may contain work items for several persons, and you want to hand out some of the sheets to person A, some sheets to person B etc.

When it is not known in advance if the printer prints duplex or not, the PDF must at some point contain empty pages in order to skip to the next physical page in duplex mode.  However, in simplex mode, this results in superfluous empty pages printed.

It should be possible to specify that a /Page resource starts at a new physical page somehow.

**Comment by petervwyatt** [comment]
You want to look at "ISO 21812-1:2019 Graphic technology — Print product metadata for PDF files — Part 1: Architecture and core requirements for metadata" from ISO TC 130. This effectively links PDF to vendor-neutral job tickets such as JDF, since every printer manufacturer, each printer family/DFE/RIP and each operating system does their job ticketing very very differently.

Historically there was also Adobe PJTF (1999, Adobe Tech Note #5620) related to PDF 1.3 but I'm not aware of any support that exists today.

**Comment by hvbtup** [comment]
Thanks for this hint. I can hjust read the abstract and it looks like it could deal with this topic.
Unofrtunately this document is behind a paywall (unlike the PDF specification).
**This kind of policy very effectively prevents open source developers from developing conforming software.**
